// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/chat_thread.proto

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Creates a message in a thread.
 * If the specified bot_name does not match an existing bot in the channel,
 * a new bot is automatically created with that name.
 * Returns 404 if the thread does not exist.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.CreateChatThreadMessageRequest}
 */
public final class CreateChatThreadMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.service.CreateChatThreadMessageRequest)
    CreateChatThreadMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateChatThreadMessageRequest.newBuilder() to construct.
  private CreateChatThreadMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateChatThreadMessageRequest() {
    channelId_ = "";
    chatType_ = "";
    chatId_ = "";
    messageId_ = "";
    botName_ = "";
    requestId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateChatThreadMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateChatThreadMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            channelId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            chatType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            chatId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            messageId_ = s;
            break;
          }
          case 42: {
            io.channel.api.proto.pub.coreapi.model.MessageContent.Builder subBuilder = null;
            if (content_ != null) {
              subBuilder = content_.toBuilder();
            }
            content_ = input.readMessage(io.channel.api.proto.pub.coreapi.model.MessageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(content_);
              content_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            botName_ = s;
            break;
          }
          case 56: {

            broadcast_ = input.readBool();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.ChatThread.internal_static_coreapi_service_CreateChatThreadMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.ChatThread.internal_static_coreapi_service_CreateChatThreadMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.class, io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.Builder.class);
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object channelId_;
  /**
   * <pre>
   * Channel ID the chat belongs to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Channel ID the chat belongs to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAT_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object chatType_;
  /**
   * <pre>
   * Chat type containing the message (e.g. "userChat", "group").
   * </pre>
   *
   * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
   * @return The chatType.
   */
  @java.lang.Override
  public java.lang.String getChatType() {
    java.lang.Object ref = chatType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Chat type containing the message (e.g. "userChat", "group").
   * </pre>
   *
   * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
   * @return The bytes for chatType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatTypeBytes() {
    java.lang.Object ref = chatType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAT_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object chatId_;
  /**
   * <pre>
   * Chat ID containing the message.
   * </pre>
   *
   * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
   * @return The chatId.
   */
  @java.lang.Override
  public java.lang.String getChatId() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Chat ID containing the message.
   * </pre>
   *
   * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for chatId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatIdBytes() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object messageId_;
  /**
   * <pre>
   * Root message ID of the thread.
   * </pre>
   *
   * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Root message ID of the thread.
   * </pre>
   *
   * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  private io.channel.api.proto.pub.coreapi.model.MessageContent content_;
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return content_ != null;
  }
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
   * @return The content.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageContent getContent() {
    return content_ == null ? io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
  }
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder getContentOrBuilder() {
    return getContent();
  }

  public static final int BOT_NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object botName_;
  /**
   * <pre>
   * Bot name to use as the message author.
   * If a bot with this name does not exist in the channel, one is created automatically.
   * +kubebuilder:validation:Nullable
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The botName.
   */
  @java.lang.Override
  public java.lang.String getBotName() {
    java.lang.Object ref = botName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      botName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Bot name to use as the message author.
   * If a bot with this name does not exist in the channel, one is created automatically.
   * +kubebuilder:validation:Nullable
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for botName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBotNameBytes() {
    java.lang.Object ref = botName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      botName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROADCAST_FIELD_NUMBER = 7;
  private boolean broadcast_;
  /**
   * <pre>
   * Whether to also post this message to the main chat stream.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool broadcast = 7 [json_name = "broadcast"];</code>
   * @return The broadcast.
   */
  @java.lang.Override
  public boolean getBroadcast() {
    return broadcast_;
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object requestId_;
  /**
   * <pre>
   * Client-generated request identifier for idempotency.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string request_id = 8 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Client-generated request identifier for idempotency.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string request_id = 8 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chatType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chatId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageId_);
    }
    if (content_ != null) {
      output.writeMessage(5, getContent());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(botName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, botName_);
    }
    if (broadcast_ != false) {
      output.writeBool(7, broadcast_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, requestId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chatType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chatId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageId_);
    }
    if (content_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getContent());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(botName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, botName_);
    }
    if (broadcast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, broadcast_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, requestId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest other = (io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest) obj;

    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (!getChatType()
        .equals(other.getChatType())) return false;
    if (!getChatId()
        .equals(other.getChatId())) return false;
    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (!getBotName()
        .equals(other.getBotName())) return false;
    if (getBroadcast()
        != other.getBroadcast()) return false;
    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType().hashCode();
    hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChatId().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    hash = (37 * hash) + BOT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBotName().hashCode();
    hash = (37 * hash) + BROADCAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBroadcast());
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Creates a message in a thread.
   * If the specified bot_name does not match an existing bot in the channel,
   * a new bot is automatically created with that name.
   * Returns 404 if the thread does not exist.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.CreateChatThreadMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.CreateChatThreadMessageRequest)
      io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.ChatThread.internal_static_coreapi_service_CreateChatThreadMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.ChatThread.internal_static_coreapi_service_CreateChatThreadMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.class, io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      channelId_ = "";

      chatType_ = "";

      chatId_ = "";

      messageId_ = "";

      if (contentBuilder_ == null) {
        content_ = null;
      } else {
        content_ = null;
        contentBuilder_ = null;
      }
      botName_ = "";

      broadcast_ = false;

      requestId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.ChatThread.internal_static_coreapi_service_CreateChatThreadMessageRequest_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest build() {
      io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest buildPartial() {
      io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest result = new io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest(this);
      result.channelId_ = channelId_;
      result.chatType_ = chatType_;
      result.chatId_ = chatId_;
      result.messageId_ = messageId_;
      if (contentBuilder_ == null) {
        result.content_ = content_;
      } else {
        result.content_ = contentBuilder_.build();
      }
      result.botName_ = botName_;
      result.broadcast_ = broadcast_;
      result.requestId_ = requestId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest other) {
      if (other == io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest.getDefaultInstance()) return this;
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        onChanged();
      }
      if (!other.getChatType().isEmpty()) {
        chatType_ = other.chatType_;
        onChanged();
      }
      if (!other.getChatId().isEmpty()) {
        chatId_ = other.chatId_;
        onChanged();
      }
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        onChanged();
      }
      if (other.hasContent()) {
        mergeContent(other.getContent());
      }
      if (!other.getBotName().isEmpty()) {
        botName_ = other.botName_;
        onChanged();
      }
      if (other.getBroadcast() != false) {
        setBroadcast(other.getBroadcast());
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <pre>
     * Channel ID the chat belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the chat belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the chat belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the chat belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      
      channelId_ = getDefaultInstance().getChannelId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the chat belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channelId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chatType_ = "";
    /**
     * <pre>
     * Chat type containing the message (e.g. "userChat", "group").
     * </pre>
     *
     * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
     * @return The chatType.
     */
    public java.lang.String getChatType() {
      java.lang.Object ref = chatType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Chat type containing the message (e.g. "userChat", "group").
     * </pre>
     *
     * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
     * @return The bytes for chatType.
     */
    public com.google.protobuf.ByteString
        getChatTypeBytes() {
      java.lang.Object ref = chatType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Chat type containing the message (e.g. "userChat", "group").
     * </pre>
     *
     * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Chat type containing the message (e.g. "userChat", "group").
     * </pre>
     *
     * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      
      chatType_ = getDefaultInstance().getChatType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Chat type containing the message (e.g. "userChat", "group").
     * </pre>
     *
     * <code>string chat_type = 2 [json_name = "chatType", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chatId_ = "";
    /**
     * <pre>
     * Chat ID containing the message.
     * </pre>
     *
     * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
     * @return The chatId.
     */
    public java.lang.String getChatId() {
      java.lang.Object ref = chatId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Chat ID containing the message.
     * </pre>
     *
     * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for chatId.
     */
    public com.google.protobuf.ByteString
        getChatIdBytes() {
      java.lang.Object ref = chatId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Chat ID containing the message.
     * </pre>
     *
     * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Chat ID containing the message.
     * </pre>
     *
     * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      
      chatId_ = getDefaultInstance().getChatId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Chat ID containing the message.
     * </pre>
     *
     * <code>string chat_id = 3 [json_name = "chatId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = getDefaultInstance().getMessageId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 4 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageId_ = value;
      onChanged();
      return this;
    }

    private io.channel.api.proto.pub.coreapi.model.MessageContent content_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder> contentBuilder_;
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return contentBuilder_ != null || content_ != null;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     * @return The content.
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContent getContent() {
      if (contentBuilder_ == null) {
        return content_ == null ? io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
      } else {
        return contentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        contentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContent(
        io.channel.api.proto.pub.coreapi.model.MessageContent.Builder builderForValue) {
      if (contentBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        contentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
      if (contentBuilder_ == null) {
        if (content_ != null) {
          content_ =
            io.channel.api.proto.pub.coreapi.model.MessageContent.newBuilder(content_).mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        contentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearContent() {
      if (contentBuilder_ == null) {
        content_ = null;
        onChanged();
      } else {
        content_ = null;
        contentBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContent.Builder getContentBuilder() {
      
      onChanged();
      return getContentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder getContentOrBuilder() {
      if (contentBuilder_ != null) {
        return contentBuilder_.getMessageOrBuilder();
      } else {
        return content_ == null ?
            io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
      }
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 5 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder> 
        getContentFieldBuilder() {
      if (contentBuilder_ == null) {
        contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder>(
                getContent(),
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      return contentBuilder_;
    }

    private java.lang.Object botName_ = "";
    /**
     * <pre>
     * Bot name to use as the message author.
     * If a bot with this name does not exist in the channel, one is created automatically.
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return The botName.
     */
    public java.lang.String getBotName() {
      java.lang.Object ref = botName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        botName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     * If a bot with this name does not exist in the channel, one is created automatically.
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return The bytes for botName.
     */
    public com.google.protobuf.ByteString
        getBotNameBytes() {
      java.lang.Object ref = botName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        botName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     * If a bot with this name does not exist in the channel, one is created automatically.
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @param value The botName to set.
     * @return This builder for chaining.
     */
    public Builder setBotName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      botName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     * If a bot with this name does not exist in the channel, one is created automatically.
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBotName() {
      
      botName_ = getDefaultInstance().getBotName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     * If a bot with this name does not exist in the channel, one is created automatically.
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 6 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for botName to set.
     * @return This builder for chaining.
     */
    public Builder setBotNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      botName_ = value;
      onChanged();
      return this;
    }

    private boolean broadcast_ ;
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 7 [json_name = "broadcast"];</code>
     * @return The broadcast.
     */
    @java.lang.Override
    public boolean getBroadcast() {
      return broadcast_;
    }
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 7 [json_name = "broadcast"];</code>
     * @param value The broadcast to set.
     * @return This builder for chaining.
     */
    public Builder setBroadcast(boolean value) {
      
      broadcast_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 7 [json_name = "broadcast"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBroadcast() {
      
      broadcast_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 8 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 8 [json_name = "requestId"];</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 8 [json_name = "requestId"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 8 [json_name = "requestId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 8 [json_name = "requestId"];</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The channel_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChannelId(java.lang.String value) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChannelId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The chat_type to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChatType(java.lang.String value) {
    	if (value == null)
    		return clearChatType();
    	else
    		return setChatType(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChatType(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChatType();
    	else
    		return setChatType(mapFunc.apply(value));
    }
    	
    /**
     * @param value The chat_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChatId(java.lang.String value) {
    	if (value == null)
    		return clearChatId();
    	else
    		return setChatId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChatId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChatId();
    	else
    		return setChatId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The message_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearMessageId(java.lang.String value) {
    	if (value == null)
    		return clearMessageId();
    	else
    		return setMessageId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearMessageId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearMessageId();
    	else
    		return setMessageId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
    	if (value == null)
    		return clearContent();
    	else
    		return setContent(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearContent(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.MessageContent> mapFunc) {
    	if (value == null)
    		return clearContent();
    	else
    		return setContent(mapFunc.apply(value));
    }
    	
    /**
     * @param value The bot_name to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBotName(java.lang.String value) {
    	if (value == null)
    		return clearBotName();
    	else
    		return setBotName(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBotName(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearBotName();
    	else
    		return setBotName(mapFunc.apply(value));
    }
    	
    /**
     * @param value The broadcast to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBroadcast(java.lang.Boolean value) {
    	if (value == null)
    		return clearBroadcast();
    	else
    		return setBroadcast(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBroadcast(T value, java.util.function.Function<T, java.lang.Boolean> mapFunc) {
    	if (value == null)
    		return clearBroadcast();
    	else
    		return setBroadcast(mapFunc.apply(value));
    }
    	
    /**
     * @param value The request_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearRequestId(java.lang.String value) {
    	if (value == null)
    		return clearRequestId();
    	else
    		return setRequestId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearRequestId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearRequestId();
    	else
    		return setRequestId(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.CreateChatThreadMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.CreateChatThreadMessageRequest)
  private static final io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest();
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateChatThreadMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateChatThreadMessageRequest>() {
    @java.lang.Override
    public CreateChatThreadMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateChatThreadMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateChatThreadMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateChatThreadMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.CreateChatThreadMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
