// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/user.proto

package io.channel.api.proto.pub.coreapi.service;

public interface DeleteUserResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.DeleteUserResult)
    com.google.protobuf.MessageOrBuilder {
}
