// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/campaign.proto

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Response for single campaign retrieval.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.GetCampaignResult}
 */
public final class GetCampaignResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.service.GetCampaignResult)
    GetCampaignResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCampaignResult.newBuilder() to construct.
  private GetCampaignResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCampaignResult() {
    campaignMsgs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCampaignResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetCampaignResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.channel.api.proto.pub.coreapi.model.Campaign.Builder subBuilder = null;
            if (campaign_ != null) {
              subBuilder = campaign_.toBuilder();
            }
            campaign_ = input.readMessage(io.channel.api.proto.pub.coreapi.model.Campaign.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(campaign_);
              campaign_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              campaignMsgs_ = new java.util.ArrayList<io.channel.api.proto.pub.coreapi.model.CampaignMsg>();
              mutable_bitField0_ |= 0x00000001;
            }
            campaignMsgs_.add(
                input.readMessage(io.channel.api.proto.pub.coreapi.model.CampaignMsg.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        campaignMsgs_ = java.util.Collections.unmodifiableList(campaignMsgs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.Campaign.internal_static_coreapi_service_GetCampaignResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.Campaign.internal_static_coreapi_service_GetCampaignResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.GetCampaignResult.class, io.channel.api.proto.pub.coreapi.service.GetCampaignResult.Builder.class);
  }

  public static final int CAMPAIGN_FIELD_NUMBER = 1;
  private io.channel.api.proto.pub.coreapi.model.Campaign campaign_;
  /**
   * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
   * @return Whether the campaign field is set.
   */
  @java.lang.Override
  public boolean hasCampaign() {
    return campaign_ != null;
  }
  /**
   * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
   * @return The campaign.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.Campaign getCampaign() {
    return campaign_ == null ? io.channel.api.proto.pub.coreapi.model.Campaign.getDefaultInstance() : campaign_;
  }
  /**
   * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.CampaignOrBuilder getCampaignOrBuilder() {
    return getCampaign();
  }

  public static final int CAMPAIGN_MSGS_FIELD_NUMBER = 2;
  private java.util.List<io.channel.api.proto.pub.coreapi.model.CampaignMsg> campaignMsgs_;
  /**
   * <pre>
   * Messages associated with this campaign.
   * </pre>
   *
   * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
   */
  @java.lang.Override
  public java.util.List<io.channel.api.proto.pub.coreapi.model.CampaignMsg> getCampaignMsgsList() {
    return campaignMsgs_;
  }
  /**
   * <pre>
   * Messages associated with this campaign.
   * </pre>
   *
   * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder> 
      getCampaignMsgsOrBuilderList() {
    return campaignMsgs_;
  }
  /**
   * <pre>
   * Messages associated with this campaign.
   * </pre>
   *
   * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
   */
  @java.lang.Override
  public int getCampaignMsgsCount() {
    return campaignMsgs_.size();
  }
  /**
   * <pre>
   * Messages associated with this campaign.
   * </pre>
   *
   * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.CampaignMsg getCampaignMsgs(int index) {
    return campaignMsgs_.get(index);
  }
  /**
   * <pre>
   * Messages associated with this campaign.
   * </pre>
   *
   * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder getCampaignMsgsOrBuilder(
      int index) {
    return campaignMsgs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (campaign_ != null) {
      output.writeMessage(1, getCampaign());
    }
    for (int i = 0; i < campaignMsgs_.size(); i++) {
      output.writeMessage(2, campaignMsgs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (campaign_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCampaign());
    }
    for (int i = 0; i < campaignMsgs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, campaignMsgs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.GetCampaignResult)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.GetCampaignResult other = (io.channel.api.proto.pub.coreapi.service.GetCampaignResult) obj;

    if (hasCampaign() != other.hasCampaign()) return false;
    if (hasCampaign()) {
      if (!getCampaign()
          .equals(other.getCampaign())) return false;
    }
    if (!getCampaignMsgsList()
        .equals(other.getCampaignMsgsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCampaign()) {
      hash = (37 * hash) + CAMPAIGN_FIELD_NUMBER;
      hash = (53 * hash) + getCampaign().hashCode();
    }
    if (getCampaignMsgsCount() > 0) {
      hash = (37 * hash) + CAMPAIGN_MSGS_FIELD_NUMBER;
      hash = (53 * hash) + getCampaignMsgsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.GetCampaignResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for single campaign retrieval.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.GetCampaignResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.GetCampaignResult)
      io.channel.api.proto.pub.coreapi.service.GetCampaignResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.Campaign.internal_static_coreapi_service_GetCampaignResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.Campaign.internal_static_coreapi_service_GetCampaignResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.GetCampaignResult.class, io.channel.api.proto.pub.coreapi.service.GetCampaignResult.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.GetCampaignResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCampaignMsgsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (campaignBuilder_ == null) {
        campaign_ = null;
      } else {
        campaign_ = null;
        campaignBuilder_ = null;
      }
      if (campaignMsgsBuilder_ == null) {
        campaignMsgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        campaignMsgsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.Campaign.internal_static_coreapi_service_GetCampaignResult_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.GetCampaignResult getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.GetCampaignResult.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.GetCampaignResult build() {
      io.channel.api.proto.pub.coreapi.service.GetCampaignResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.GetCampaignResult buildPartial() {
      io.channel.api.proto.pub.coreapi.service.GetCampaignResult result = new io.channel.api.proto.pub.coreapi.service.GetCampaignResult(this);
      int from_bitField0_ = bitField0_;
      if (campaignBuilder_ == null) {
        result.campaign_ = campaign_;
      } else {
        result.campaign_ = campaignBuilder_.build();
      }
      if (campaignMsgsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          campaignMsgs_ = java.util.Collections.unmodifiableList(campaignMsgs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.campaignMsgs_ = campaignMsgs_;
      } else {
        result.campaignMsgs_ = campaignMsgsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.GetCampaignResult) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.GetCampaignResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.GetCampaignResult other) {
      if (other == io.channel.api.proto.pub.coreapi.service.GetCampaignResult.getDefaultInstance()) return this;
      if (other.hasCampaign()) {
        mergeCampaign(other.getCampaign());
      }
      if (campaignMsgsBuilder_ == null) {
        if (!other.campaignMsgs_.isEmpty()) {
          if (campaignMsgs_.isEmpty()) {
            campaignMsgs_ = other.campaignMsgs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCampaignMsgsIsMutable();
            campaignMsgs_.addAll(other.campaignMsgs_);
          }
          onChanged();
        }
      } else {
        if (!other.campaignMsgs_.isEmpty()) {
          if (campaignMsgsBuilder_.isEmpty()) {
            campaignMsgsBuilder_.dispose();
            campaignMsgsBuilder_ = null;
            campaignMsgs_ = other.campaignMsgs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            campaignMsgsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCampaignMsgsFieldBuilder() : null;
          } else {
            campaignMsgsBuilder_.addAllMessages(other.campaignMsgs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.service.GetCampaignResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.service.GetCampaignResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.channel.api.proto.pub.coreapi.model.Campaign campaign_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.Campaign, io.channel.api.proto.pub.coreapi.model.Campaign.Builder, io.channel.api.proto.pub.coreapi.model.CampaignOrBuilder> campaignBuilder_;
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     * @return Whether the campaign field is set.
     */
    public boolean hasCampaign() {
      return campaignBuilder_ != null || campaign_ != null;
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     * @return The campaign.
     */
    public io.channel.api.proto.pub.coreapi.model.Campaign getCampaign() {
      if (campaignBuilder_ == null) {
        return campaign_ == null ? io.channel.api.proto.pub.coreapi.model.Campaign.getDefaultInstance() : campaign_;
      } else {
        return campaignBuilder_.getMessage();
      }
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public Builder setCampaign(io.channel.api.proto.pub.coreapi.model.Campaign value) {
      if (campaignBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        campaign_ = value;
        onChanged();
      } else {
        campaignBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public Builder setCampaign(
        io.channel.api.proto.pub.coreapi.model.Campaign.Builder builderForValue) {
      if (campaignBuilder_ == null) {
        campaign_ = builderForValue.build();
        onChanged();
      } else {
        campaignBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public Builder mergeCampaign(io.channel.api.proto.pub.coreapi.model.Campaign value) {
      if (campaignBuilder_ == null) {
        if (campaign_ != null) {
          campaign_ =
            io.channel.api.proto.pub.coreapi.model.Campaign.newBuilder(campaign_).mergeFrom(value).buildPartial();
        } else {
          campaign_ = value;
        }
        onChanged();
      } else {
        campaignBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public Builder clearCampaign() {
      if (campaignBuilder_ == null) {
        campaign_ = null;
        onChanged();
      } else {
        campaign_ = null;
        campaignBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.Campaign.Builder getCampaignBuilder() {
      
      onChanged();
      return getCampaignFieldBuilder().getBuilder();
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignOrBuilder getCampaignOrBuilder() {
      if (campaignBuilder_ != null) {
        return campaignBuilder_.getMessageOrBuilder();
      } else {
        return campaign_ == null ?
            io.channel.api.proto.pub.coreapi.model.Campaign.getDefaultInstance() : campaign_;
      }
    }
    /**
     * <code>.coreapi.model.Campaign campaign = 1 [json_name = "campaign"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.Campaign, io.channel.api.proto.pub.coreapi.model.Campaign.Builder, io.channel.api.proto.pub.coreapi.model.CampaignOrBuilder> 
        getCampaignFieldBuilder() {
      if (campaignBuilder_ == null) {
        campaignBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.channel.api.proto.pub.coreapi.model.Campaign, io.channel.api.proto.pub.coreapi.model.Campaign.Builder, io.channel.api.proto.pub.coreapi.model.CampaignOrBuilder>(
                getCampaign(),
                getParentForChildren(),
                isClean());
        campaign_ = null;
      }
      return campaignBuilder_;
    }

    private java.util.List<io.channel.api.proto.pub.coreapi.model.CampaignMsg> campaignMsgs_ =
      java.util.Collections.emptyList();
    private void ensureCampaignMsgsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        campaignMsgs_ = new java.util.ArrayList<io.channel.api.proto.pub.coreapi.model.CampaignMsg>(campaignMsgs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.CampaignMsg, io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder, io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder> campaignMsgsBuilder_;

    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public java.util.List<io.channel.api.proto.pub.coreapi.model.CampaignMsg> getCampaignMsgsList() {
      if (campaignMsgsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(campaignMsgs_);
      } else {
        return campaignMsgsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public int getCampaignMsgsCount() {
      if (campaignMsgsBuilder_ == null) {
        return campaignMsgs_.size();
      } else {
        return campaignMsgsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignMsg getCampaignMsgs(int index) {
      if (campaignMsgsBuilder_ == null) {
        return campaignMsgs_.get(index);
      } else {
        return campaignMsgsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder setCampaignMsgs(
        int index, io.channel.api.proto.pub.coreapi.model.CampaignMsg value) {
      if (campaignMsgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.set(index, value);
        onChanged();
      } else {
        campaignMsgsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder setCampaignMsgs(
        int index, io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder builderForValue) {
      if (campaignMsgsBuilder_ == null) {
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.set(index, builderForValue.build());
        onChanged();
      } else {
        campaignMsgsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder addCampaignMsgs(io.channel.api.proto.pub.coreapi.model.CampaignMsg value) {
      if (campaignMsgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.add(value);
        onChanged();
      } else {
        campaignMsgsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder addCampaignMsgs(
        int index, io.channel.api.proto.pub.coreapi.model.CampaignMsg value) {
      if (campaignMsgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.add(index, value);
        onChanged();
      } else {
        campaignMsgsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder addCampaignMsgs(
        io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder builderForValue) {
      if (campaignMsgsBuilder_ == null) {
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.add(builderForValue.build());
        onChanged();
      } else {
        campaignMsgsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder addCampaignMsgs(
        int index, io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder builderForValue) {
      if (campaignMsgsBuilder_ == null) {
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.add(index, builderForValue.build());
        onChanged();
      } else {
        campaignMsgsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder addAllCampaignMsgs(
        java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.CampaignMsg> values) {
      if (campaignMsgsBuilder_ == null) {
        ensureCampaignMsgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, campaignMsgs_);
        onChanged();
      } else {
        campaignMsgsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder clearCampaignMsgs() {
      if (campaignMsgsBuilder_ == null) {
        campaignMsgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        campaignMsgsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public Builder removeCampaignMsgs(int index) {
      if (campaignMsgsBuilder_ == null) {
        ensureCampaignMsgsIsMutable();
        campaignMsgs_.remove(index);
        onChanged();
      } else {
        campaignMsgsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder getCampaignMsgsBuilder(
        int index) {
      return getCampaignMsgsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder getCampaignMsgsOrBuilder(
        int index) {
      if (campaignMsgsBuilder_ == null) {
        return campaignMsgs_.get(index);  } else {
        return campaignMsgsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public java.util.List<? extends io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder> 
         getCampaignMsgsOrBuilderList() {
      if (campaignMsgsBuilder_ != null) {
        return campaignMsgsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(campaignMsgs_);
      }
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder addCampaignMsgsBuilder() {
      return getCampaignMsgsFieldBuilder().addBuilder(
          io.channel.api.proto.pub.coreapi.model.CampaignMsg.getDefaultInstance());
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder addCampaignMsgsBuilder(
        int index) {
      return getCampaignMsgsFieldBuilder().addBuilder(
          index, io.channel.api.proto.pub.coreapi.model.CampaignMsg.getDefaultInstance());
    }
    /**
     * <pre>
     * Messages associated with this campaign.
     * </pre>
     *
     * <code>repeated .coreapi.model.CampaignMsg campaign_msgs = 2 [json_name = "campaignMsgs"];</code>
     */
    public java.util.List<io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder> 
         getCampaignMsgsBuilderList() {
      return getCampaignMsgsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.CampaignMsg, io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder, io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder> 
        getCampaignMsgsFieldBuilder() {
      if (campaignMsgsBuilder_ == null) {
        campaignMsgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.channel.api.proto.pub.coreapi.model.CampaignMsg, io.channel.api.proto.pub.coreapi.model.CampaignMsg.Builder, io.channel.api.proto.pub.coreapi.model.CampaignMsgOrBuilder>(
                campaignMsgs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        campaignMsgs_ = null;
      }
      return campaignMsgsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The campaign to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearCampaign(io.channel.api.proto.pub.coreapi.model.Campaign value) {
    	if (value == null)
    		return clearCampaign();
    	else
    		return setCampaign(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearCampaign(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.Campaign> mapFunc) {
    	if (value == null)
    		return clearCampaign();
    	else
    		return setCampaign(mapFunc.apply(value));
    }
    	
    /**
     * @param values The campaign_msgs to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrClearCampaignMsgs(java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.CampaignMsg> values) {
    	if (values == null)
    		return clearCampaignMsgs();
    	else
    		return addAllCampaignMsgs(values);
    }
    	
    /**
     * @param values The values to map.
     * @param mapFunc The function to map the values into each proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapAllOrClearCampaignMsgs(java.lang.Iterable<T> values, java.util.function.Function<T, ? extends io.channel.api.proto.pub.coreapi.model.CampaignMsg> mapFunc) {
    	if (values == null)
    		return clearCampaignMsgs();
    	else {
    		values.forEach(value -> addCampaignMsgs(mapFunc.apply(value)));
    		return this;
    	}
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.GetCampaignResult)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.GetCampaignResult)
  private static final io.channel.api.proto.pub.coreapi.service.GetCampaignResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.GetCampaignResult();
  }

  public static io.channel.api.proto.pub.coreapi.service.GetCampaignResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCampaignResult>
      PARSER = new com.google.protobuf.AbstractParser<GetCampaignResult>() {
    @java.lang.Override
    public GetCampaignResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetCampaignResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetCampaignResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCampaignResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.GetCampaignResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
