// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/user.proto

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Response for user token issuance by member identifier.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.IssueUserTokenByMemberIdResult}
 */
public final class IssueUserTokenByMemberIdResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.service.IssueUserTokenByMemberIdResult)
    IssueUserTokenByMemberIdResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IssueUserTokenByMemberIdResult.newBuilder() to construct.
  private IssueUserTokenByMemberIdResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IssueUserTokenByMemberIdResult() {
    token_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IssueUserTokenByMemberIdResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IssueUserTokenByMemberIdResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (disableAt_ != null) {
              subBuilder = disableAt_.toBuilder();
            }
            disableAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(disableAt_);
              disableAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_IssueUserTokenByMemberIdResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_IssueUserTokenByMemberIdResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.class, io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.Builder.class);
  }

  public static final int TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   * Issued user token.
   * </pre>
   *
   * <code>string token = 1 [json_name = "token"];</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Issued user token.
   * </pre>
   *
   * <code>string token = 1 [json_name = "token"];</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISABLE_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp disableAt_;
  /**
   * <pre>
   * Timestamp when the token becomes disabled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
   * @return Whether the disableAt field is set.
   */
  @java.lang.Override
  public boolean hasDisableAt() {
    return disableAt_ != null;
  }
  /**
   * <pre>
   * Timestamp when the token becomes disabled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
   * @return The disableAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDisableAt() {
    return disableAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : disableAt_;
  }
  /**
   * <pre>
   * Timestamp when the token becomes disabled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDisableAtOrBuilder() {
    return getDisableAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
    }
    if (disableAt_ != null) {
      output.writeMessage(2, getDisableAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
    }
    if (disableAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDisableAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult other = (io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult) obj;

    if (!getToken()
        .equals(other.getToken())) return false;
    if (hasDisableAt() != other.hasDisableAt()) return false;
    if (hasDisableAt()) {
      if (!getDisableAt()
          .equals(other.getDisableAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    if (hasDisableAt()) {
      hash = (37 * hash) + DISABLE_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDisableAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for user token issuance by member identifier.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.IssueUserTokenByMemberIdResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.IssueUserTokenByMemberIdResult)
      io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_IssueUserTokenByMemberIdResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_IssueUserTokenByMemberIdResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.class, io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      token_ = "";

      if (disableAtBuilder_ == null) {
        disableAt_ = null;
      } else {
        disableAt_ = null;
        disableAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_IssueUserTokenByMemberIdResult_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult build() {
      io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult buildPartial() {
      io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult result = new io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult(this);
      result.token_ = token_;
      if (disableAtBuilder_ == null) {
        result.disableAt_ = disableAt_;
      } else {
        result.disableAt_ = disableAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult other) {
      if (other == io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult.getDefaultInstance()) return this;
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (other.hasDisableAt()) {
        mergeDisableAt(other.getDisableAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     * Issued user token.
     * </pre>
     *
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Issued user token.
     * </pre>
     *
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Issued user token.
     * </pre>
     *
     * <code>string token = 1 [json_name = "token"];</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Issued user token.
     * </pre>
     *
     * <code>string token = 1 [json_name = "token"];</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Issued user token.
     * </pre>
     *
     * <code>string token = 1 [json_name = "token"];</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp disableAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> disableAtBuilder_;
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     * @return Whether the disableAt field is set.
     */
    public boolean hasDisableAt() {
      return disableAtBuilder_ != null || disableAt_ != null;
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     * @return The disableAt.
     */
    public com.google.protobuf.Timestamp getDisableAt() {
      if (disableAtBuilder_ == null) {
        return disableAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : disableAt_;
      } else {
        return disableAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public Builder setDisableAt(com.google.protobuf.Timestamp value) {
      if (disableAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        disableAt_ = value;
        onChanged();
      } else {
        disableAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public Builder setDisableAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (disableAtBuilder_ == null) {
        disableAt_ = builderForValue.build();
        onChanged();
      } else {
        disableAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public Builder mergeDisableAt(com.google.protobuf.Timestamp value) {
      if (disableAtBuilder_ == null) {
        if (disableAt_ != null) {
          disableAt_ =
            com.google.protobuf.Timestamp.newBuilder(disableAt_).mergeFrom(value).buildPartial();
        } else {
          disableAt_ = value;
        }
        onChanged();
      } else {
        disableAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public Builder clearDisableAt() {
      if (disableAtBuilder_ == null) {
        disableAt_ = null;
        onChanged();
      } else {
        disableAt_ = null;
        disableAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getDisableAtBuilder() {
      
      onChanged();
      return getDisableAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDisableAtOrBuilder() {
      if (disableAtBuilder_ != null) {
        return disableAtBuilder_.getMessageOrBuilder();
      } else {
        return disableAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : disableAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when the token becomes disabled.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp disable_at = 2 [json_name = "disableAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDisableAtFieldBuilder() {
      if (disableAtBuilder_ == null) {
        disableAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDisableAt(),
                getParentForChildren(),
                isClean());
        disableAt_ = null;
      }
      return disableAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearToken(java.lang.String value) {
    	if (value == null)
    		return clearToken();
    	else
    		return setToken(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearToken(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearToken();
    	else
    		return setToken(mapFunc.apply(value));
    }
    	
    /**
     * @param value The disable_at to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearDisableAt(com.google.protobuf.Timestamp value) {
    	if (value == null)
    		return clearDisableAt();
    	else
    		return setDisableAt(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearDisableAt(T value, java.util.function.Function<T, com.google.protobuf.Timestamp> mapFunc) {
    	if (value == null)
    		return clearDisableAt();
    	else
    		return setDisableAt(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.IssueUserTokenByMemberIdResult)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.IssueUserTokenByMemberIdResult)
  private static final io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult();
  }

  public static io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IssueUserTokenByMemberIdResult>
      PARSER = new com.google.protobuf.AbstractParser<IssueUserTokenByMemberIdResult>() {
    @java.lang.Override
    public IssueUserTokenByMemberIdResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IssueUserTokenByMemberIdResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IssueUserTokenByMemberIdResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IssueUserTokenByMemberIdResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.IssueUserTokenByMemberIdResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
