// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/user_chat.proto

package io.channel.api.proto.pub.coreapi.service;

public interface SnoozeUserChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.SnoozeUserChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User chat ID to snooze.
   * </pre>
   *
   * <code>string user_chat_id = 1 [json_name = "userChatId", (.buf.validate.field) = { ... }</code>
   * @return The userChatId.
   */
  java.lang.String getUserChatId();
  /**
   * <pre>
   * User chat ID to snooze.
   * </pre>
   *
   * <code>string user_chat_id = 1 [json_name = "userChatId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for userChatId.
   */
  com.google.protobuf.ByteString
      getUserChatIdBytes();

  /**
   * <pre>
   * Channel ID the user chat belongs to.
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <pre>
   * Channel ID the user chat belongs to.
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <pre>
   * Name of the bot that snoozes the user chat.
   * Creates a new bot if one with this name does not exist.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 3 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The botName.
   */
  java.lang.String getBotName();
  /**
   * <pre>
   * Name of the bot that snoozes the user chat.
   * Creates a new bot if one with this name does not exist.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 3 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for botName.
   */
  com.google.protobuf.ByteString
      getBotNameBytes();

  /**
   * <pre>
   * Duration to snooze the user chat.
   * Must be at least 1 minute.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 4 [json_name = "duration", (.buf.validate.field) = { ... }</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <pre>
   * Duration to snooze the user chat.
   * Must be at least 1 minute.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 4 [json_name = "duration", (.buf.validate.field) = { ... }</code>
   * @return The duration.
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <pre>
   * Duration to snooze the user chat.
   * Must be at least 1 minute.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 4 [json_name = "duration", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();
}
