// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/user.proto

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Response for user upsert by member identifier.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.UpsertUserByMemberIdResult}
 */
public final class UpsertUserByMemberIdResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.service.UpsertUserByMemberIdResult)
    UpsertUserByMemberIdResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpsertUserByMemberIdResult.newBuilder() to construct.
  private UpsertUserByMemberIdResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpsertUserByMemberIdResult() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpsertUserByMemberIdResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpsertUserByMemberIdResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.channel.api.proto.pub.coreapi.model.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(io.channel.api.proto.pub.coreapi.model.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.channel.api.proto.pub.coreapi.model.Online.Builder subBuilder = null;
            if (online_ != null) {
              subBuilder = online_.toBuilder();
            }
            online_ = input.readMessage(io.channel.api.proto.pub.coreapi.model.Online.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(online_);
              online_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_UpsertUserByMemberIdResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_UpsertUserByMemberIdResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.class, io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private io.channel.api.proto.pub.coreapi.model.User user_;
  /**
   * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.User getUser() {
    return user_ == null ? io.channel.api.proto.pub.coreapi.model.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int ONLINE_FIELD_NUMBER = 2;
  private io.channel.api.proto.pub.coreapi.model.Online online_;
  /**
   * <pre>
   * Online presence of the user.
   * </pre>
   *
   * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
   * @return Whether the online field is set.
   */
  @java.lang.Override
  public boolean hasOnline() {
    return online_ != null;
  }
  /**
   * <pre>
   * Online presence of the user.
   * </pre>
   *
   * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
   * @return The online.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.Online getOnline() {
    return online_ == null ? io.channel.api.proto.pub.coreapi.model.Online.getDefaultInstance() : online_;
  }
  /**
   * <pre>
   * Online presence of the user.
   * </pre>
   *
   * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.OnlineOrBuilder getOnlineOrBuilder() {
    return getOnline();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    if (online_ != null) {
      output.writeMessage(2, getOnline());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (online_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOnline());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult other = (io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (hasOnline() != other.hasOnline()) return false;
    if (hasOnline()) {
      if (!getOnline()
          .equals(other.getOnline())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasOnline()) {
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + getOnline().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for user upsert by member identifier.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.UpsertUserByMemberIdResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.UpsertUserByMemberIdResult)
      io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_UpsertUserByMemberIdResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_UpsertUserByMemberIdResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.class, io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (onlineBuilder_ == null) {
        online_ = null;
      } else {
        online_ = null;
        onlineBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.User.internal_static_coreapi_service_UpsertUserByMemberIdResult_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult build() {
      io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult buildPartial() {
      io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult result = new io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (onlineBuilder_ == null) {
        result.online_ = online_;
      } else {
        result.online_ = onlineBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult other) {
      if (other == io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasOnline()) {
        mergeOnline(other.getOnline());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.channel.api.proto.pub.coreapi.model.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.User, io.channel.api.proto.pub.coreapi.model.User.Builder, io.channel.api.proto.pub.coreapi.model.UserOrBuilder> userBuilder_;
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     * @return The user.
     */
    public io.channel.api.proto.pub.coreapi.model.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? io.channel.api.proto.pub.coreapi.model.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public Builder setUser(io.channel.api.proto.pub.coreapi.model.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public Builder setUser(
        io.channel.api.proto.pub.coreapi.model.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public Builder mergeUser(io.channel.api.proto.pub.coreapi.model.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            io.channel.api.proto.pub.coreapi.model.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            io.channel.api.proto.pub.coreapi.model.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.coreapi.model.User user = 1 [json_name = "user"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.User, io.channel.api.proto.pub.coreapi.model.User.Builder, io.channel.api.proto.pub.coreapi.model.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.channel.api.proto.pub.coreapi.model.User, io.channel.api.proto.pub.coreapi.model.User.Builder, io.channel.api.proto.pub.coreapi.model.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private io.channel.api.proto.pub.coreapi.model.Online online_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.Online, io.channel.api.proto.pub.coreapi.model.Online.Builder, io.channel.api.proto.pub.coreapi.model.OnlineOrBuilder> onlineBuilder_;
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     * @return Whether the online field is set.
     */
    public boolean hasOnline() {
      return onlineBuilder_ != null || online_ != null;
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     * @return The online.
     */
    public io.channel.api.proto.pub.coreapi.model.Online getOnline() {
      if (onlineBuilder_ == null) {
        return online_ == null ? io.channel.api.proto.pub.coreapi.model.Online.getDefaultInstance() : online_;
      } else {
        return onlineBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public Builder setOnline(io.channel.api.proto.pub.coreapi.model.Online value) {
      if (onlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        online_ = value;
        onChanged();
      } else {
        onlineBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public Builder setOnline(
        io.channel.api.proto.pub.coreapi.model.Online.Builder builderForValue) {
      if (onlineBuilder_ == null) {
        online_ = builderForValue.build();
        onChanged();
      } else {
        onlineBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public Builder mergeOnline(io.channel.api.proto.pub.coreapi.model.Online value) {
      if (onlineBuilder_ == null) {
        if (online_ != null) {
          online_ =
            io.channel.api.proto.pub.coreapi.model.Online.newBuilder(online_).mergeFrom(value).buildPartial();
        } else {
          online_ = value;
        }
        onChanged();
      } else {
        onlineBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public Builder clearOnline() {
      if (onlineBuilder_ == null) {
        online_ = null;
        onChanged();
      } else {
        online_ = null;
        onlineBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.Online.Builder getOnlineBuilder() {
      
      onChanged();
      return getOnlineFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    public io.channel.api.proto.pub.coreapi.model.OnlineOrBuilder getOnlineOrBuilder() {
      if (onlineBuilder_ != null) {
        return onlineBuilder_.getMessageOrBuilder();
      } else {
        return online_ == null ?
            io.channel.api.proto.pub.coreapi.model.Online.getDefaultInstance() : online_;
      }
    }
    /**
     * <pre>
     * Online presence of the user.
     * </pre>
     *
     * <code>.coreapi.model.Online online = 2 [json_name = "online"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.channel.api.proto.pub.coreapi.model.Online, io.channel.api.proto.pub.coreapi.model.Online.Builder, io.channel.api.proto.pub.coreapi.model.OnlineOrBuilder> 
        getOnlineFieldBuilder() {
      if (onlineBuilder_ == null) {
        onlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.channel.api.proto.pub.coreapi.model.Online, io.channel.api.proto.pub.coreapi.model.Online.Builder, io.channel.api.proto.pub.coreapi.model.OnlineOrBuilder>(
                getOnline(),
                getParentForChildren(),
                isClean());
        online_ = null;
      }
      return onlineBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The user to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearUser(io.channel.api.proto.pub.coreapi.model.User value) {
    	if (value == null)
    		return clearUser();
    	else
    		return setUser(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearUser(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.User> mapFunc) {
    	if (value == null)
    		return clearUser();
    	else
    		return setUser(mapFunc.apply(value));
    }
    	
    /**
     * @param value The online to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearOnline(io.channel.api.proto.pub.coreapi.model.Online value) {
    	if (value == null)
    		return clearOnline();
    	else
    		return setOnline(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearOnline(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.Online> mapFunc) {
    	if (value == null)
    		return clearOnline();
    	else
    		return setOnline(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.UpsertUserByMemberIdResult)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.UpsertUserByMemberIdResult)
  private static final io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult();
  }

  public static io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpsertUserByMemberIdResult>
      PARSER = new com.google.protobuf.AbstractParser<UpsertUserByMemberIdResult>() {
    @java.lang.Override
    public UpsertUserByMemberIdResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpsertUserByMemberIdResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpsertUserByMemberIdResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpsertUserByMemberIdResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.UpsertUserByMemberIdResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
