// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/user_chat.proto

package io.channel.api.proto.pub.coreapi.service;

public final class UserChat {
  private UserChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatsResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatsResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatsForUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatsForUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatsForUserResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatsForUserResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_GetUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_GetUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_GetUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_GetUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CreateUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CreateUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CreateUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CreateUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_UpdateUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_UpdateUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_UpdateUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_UpdateUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_DeleteUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_DeleteUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_DeleteUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_DeleteUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_OpenUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_OpenUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_OpenUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_OpenUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CloseUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CloseUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CloseUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CloseUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SnoozeUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SnoozeUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SnoozeUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SnoozeUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_InviteManagersToUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_InviteManagersToUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_InviteManagersToUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_InviteManagersToUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_AssignManagerToUserChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_AssignManagerToUserChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_AssignManagerToUserChatResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_AssignManagerToUserChatResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_SearchUserChatMessagesResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_SearchUserChatMessagesResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CreateUserChatMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CreateUserChatMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_service_CreateUserChatMessageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_service_CreateUserChatMessageResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037coreapi/service/user_chat.proto\022\017corea" +
      "pi.service\032\033buf/validate/validate.proto\032" +
      "\037coreapi/common/sort_order.proto\032\033coreap" +
      "i/model/message.proto\032#coreapi/model/mes" +
      "sage_content.proto\032\035coreapi/model/user_c" +
      "hat.proto\032\036google/protobuf/duration.prot" +
      "o\"\274\002\n\026SearchUserChatsRequest\022%\n\nchannel_" +
      "id\030\001 \001(\tB\006\272H\003\310\001\001R\tchannelId\0222\n\005state\030\002 \001" +
      "(\0162\034.coreapi.model.UserChatStateR\005state\022" +
      "8\n\nsort_order\030\003 \001(\0162\031.coreapi.common.Sor" +
      "tOrderR\tsortOrder\022\026\n\006cursor\030\004 \001(\tR\006curso" +
      "r\022u\n\005limit\030\005 \001(\005B_\272H\\\272\001Y\n\rint32.between\022" +
      "\037limit must be between 1 and 500\032\'this =" +
      "= 0 || (this >= 1 && this <= 500)R\005limit" +
      "\"\213\001\n\025SearchUserChatsResult\0226\n\nuser_chats" +
      "\030\001 \003(\0132\027.coreapi.model.UserChatR\tuserCha" +
      "ts\022\037\n\013next_cursor\030\002 \001(\tR\nnextCursor\022\031\n\010h" +
      "as_next\030\003 \001(\010R\007hasNext\"\260\002\n\035SearchUserCha" +
      "tsForUserRequest\022%\n\nchannel_id\030\001 \001(\tB\006\272H" +
      "\003\310\001\001R\tchannelId\022\037\n\007user_id\030\002 \001(\tB\006\272H\003\310\001\001" +
      "R\006userId\0228\n\nsort_order\030\003 \001(\0162\031.coreapi.c" +
      "ommon.SortOrderR\tsortOrder\022\026\n\006cursor\030\004 \001" +
      "(\tR\006cursor\022u\n\005limit\030\005 \001(\005B_\272H\\\272\001Y\n\rint32" +
      ".between\022\037limit must be between 1 and 50" +
      "0\032\'this == 0 || (this >= 1 && this <= 50" +
      "0)R\005limit\"\222\001\n\034SearchUserChatsForUserResu" +
      "lt\0226\n\nuser_chats\030\001 \003(\0132\027.coreapi.model.U" +
      "serChatR\tuserChats\022\037\n\013next_cursor\030\002 \001(\tR" +
      "\nnextCursor\022\031\n\010has_next\030\003 \001(\010R\007hasNext\"e" +
      "\n\022GetUserChatRequest\022(\n\014user_chat_id\030\001 \001" +
      "(\tB\006\272H\003\310\001\001R\nuserChatId\022%\n\nchannel_id\030\002 \001" +
      "(\tB\006\272H\003\310\001\001R\tchannelId\"I\n\021GetUserChatResu" +
      "lt\0224\n\tuser_chat\030\001 \001(\0132\027.coreapi.model.Us" +
      "erChatR\010userChat\"_\n\025CreateUserChatReques" +
      "t\022%\n\nchannel_id\030\001 \001(\tB\006\272H\003\310\001\001R\tchannelId" +
      "\022\037\n\007user_id\030\002 \001(\tB\006\272H\003\310\001\001R\006userId\"L\n\024Cre" +
      "ateUserChatResult\0224\n\tuser_chat\030\001 \001(\0132\027.c" +
      "oreapi.model.UserChatR\010userChat\"\341\001\n\025Upda" +
      "teUserChatRequest\022(\n\014user_chat_id\030\001 \001(\tB" +
      "\006\272H\003\310\001\001R\nuserChatId\022%\n\nchannel_id\030\002 \001(\tB" +
      "\006\272H\003\310\001\001R\tchannelId\022w\n\013description\030\003 \001(\tB" +
      "U\272HR\272\001O\n\rstring.maxLen\022*value must be no" +
      " more than 1000 characters\032\022size(this) <" +
      "= 1000R\013description\"L\n\024UpdateUserChatRes" +
      "ult\0224\n\tuser_chat\030\001 \001(\0132\027.coreapi.model.U" +
      "serChatR\010userChat\"h\n\025DeleteUserChatReque" +
      "st\022(\n\014user_chat_id\030\001 \001(\tB\006\272H\003\310\001\001R\nuserCh" +
      "atId\022%\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001\001R\tchanne" +
      "lId\"\026\n\024DeleteUserChatResult\"\261\002\n\023OpenUser" +
      "ChatRequest\022(\n\014user_chat_id\030\001 \001(\tB\006\272H\003\310\001" +
      "\001R\nuserChatId\022%\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001" +
      "\001R\tchannelId\022\310\001\n\010bot_name\030\003 \001(\tB\254\001\272H\250\001\272\001" +
      "D\n\rstring.minLen\022\"value must be at least" +
      " 1 character\032\017size(this) >= 1\272\001K\n\rstring" +
      ".maxLen\022(value must be no more than 30 c" +
      "haracters\032\020size(this) <= 30\310\001\001r\0162\014^[^@#$" +
      "%:/]+$R\007botName\"J\n\022OpenUserChatResult\0224\n" +
      "\tuser_chat\030\001 \001(\0132\027.coreapi.model.UserCha" +
      "tR\010userChat\"\262\002\n\024CloseUserChatRequest\022(\n\014" +
      "user_chat_id\030\001 \001(\tB\006\272H\003\310\001\001R\nuserChatId\022%" +
      "\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001\001R\tchannelId\022\310\001" +
      "\n\010bot_name\030\003 \001(\tB\254\001\272H\250\001\272\001D\n\rstring.minLe" +
      "n\022\"value must be at least 1 character\032\017s" +
      "ize(this) >= 1\272\001K\n\rstring.maxLen\022(value " +
      "must be no more than 30 characters\032\020size" +
      "(this) <= 30\310\001\001r\0162\014^[^@#$%:/]+$R\007botName" +
      "\"K\n\023CloseUserChatResult\0224\n\tuser_chat\030\001 \001" +
      "(\0132\027.coreapi.model.UserChatR\010userChat\"\301\003" +
      "\n\025SnoozeUserChatRequest\022(\n\014user_chat_id\030" +
      "\001 \001(\tB\006\272H\003\310\001\001R\nuserChatId\022%\n\nchannel_id\030" +
      "\002 \001(\tB\006\272H\003\310\001\001R\tchannelId\022\310\001\n\010bot_name\030\003 " +
      "\001(\tB\254\001\272H\250\001\272\001D\n\rstring.minLen\022\"value must" +
      " be at least 1 character\032\017size(this) >= " +
      "1\272\001K\n\rstring.maxLen\022(value must be no mo" +
      "re than 30 characters\032\020size(this) <= 30\310" +
      "\001\001r\0162\014^[^@#$%:/]+$R\007botName\022\213\001\n\010duration" +
      "\030\004 \001(\0132\031.google.protobuf.DurationBT\272HQ\272\001" +
      "K\n\014duration.gte\022\"duration must be at lea" +
      "st 1 minute\032\027this >= duration(\'60s\')\310\001\001R" +
      "\010duration\"L\n\024SnoozeUserChatResult\0224\n\tuse" +
      "r_chat\030\001 \001(\0132\027.coreapi.model.UserChatR\010u" +
      "serChat\"\262\003\n\037InviteManagersToUserChatRequ" +
      "est\022(\n\014user_chat_id\030\001 \001(\tB\006\272H\003\310\001\001R\nuserC" +
      "hatId\022%\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001\001R\tchann" +
      "elId\022\310\001\n\010bot_name\030\003 \001(\tB\254\001\272H\250\001\272\001D\n\rstrin" +
      "g.minLen\022\"value must be at least 1 chara" +
      "cter\032\017size(this) >= 1\272\001K\n\rstring.maxLen\022" +
      "(value must be no more than 30 character" +
      "s\032\020size(this) <= 30\310\001\001r\0162\014^[^@#$%:/]+$R\007" +
      "botName\022s\n\013manager_ids\030\004 \003(\tBR\272HO\272\001I\n\021re" +
      "peated.minItems\022#at least one manager ID" +
      " is required\032\017size(this) >= 1\310\001\001R\nmanage" +
      "rIds\"V\n\036InviteManagersToUserChatResult\0224" +
      "\n\tuser_chat\030\001 \001(\0132\027.coreapi.model.UserCh" +
      "atR\010userChat\"\343\002\n\036AssignManagerToUserChat" +
      "Request\022(\n\014user_chat_id\030\001 \001(\tB\006\272H\003\310\001\001R\nu" +
      "serChatId\022%\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001\001R\tc" +
      "hannelId\022\310\001\n\010bot_name\030\003 \001(\tB\254\001\272H\250\001\272\001D\n\rs" +
      "tring.minLen\022\"value must be at least 1 c" +
      "haracter\032\017size(this) >= 1\272\001K\n\rstring.max" +
      "Len\022(value must be no more than 30 chara" +
      "cters\032\020size(this) <= 30\310\001\001r\0162\014^[^@#$%:/]" +
      "+$R\007botName\022%\n\nmanager_id\030\004 \001(\tB\006\272H\003\310\001\001R" +
      "\tmanagerId\"U\n\035AssignManagerToUserChatRes" +
      "ult\0224\n\tuser_chat\030\001 \001(\0132\027.coreapi.model.U" +
      "serChatR\010userChat\"\271\002\n\035SearchUserChatMess" +
      "agesRequest\022(\n\014user_chat_id\030\001 \001(\tB\006\272H\003\310\001" +
      "\001R\nuserChatId\022%\n\nchannel_id\030\002 \001(\tB\006\272H\003\310\001" +
      "\001R\tchannelId\0228\n\nsort_order\030\003 \001(\0162\031.corea" +
      "pi.common.SortOrderR\tsortOrder\022\026\n\006cursor" +
      "\030\004 \001(\tR\006cursor\022u\n\005limit\030\005 \001(\005B_\272H\\\272\001Y\n\ri" +
      "nt32.between\022\037limit must be between 1 an" +
      "d 500\032\'this == 0 || (this >= 1 && this <" +
      "= 500)R\005limit\"\216\001\n\034SearchUserChatMessages" +
      "Result\0222\n\010messages\030\001 \003(\0132\026.coreapi.model" +
      ".MessageR\010messages\022\037\n\013next_cursor\030\002 \001(\tR" +
      "\nnextCursor\022\031\n\010has_next\030\003 \001(\010R\007hasNext\"\334" +
      "\002\n\034CreateUserChatMessageRequest\022(\n\014user_" +
      "chat_id\030\001 \001(\tB\006\272H\003\310\001\001R\nuserChatId\022%\n\ncha" +
      "nnel_id\030\002 \001(\tB\006\272H\003\310\001\001R\tchannelId\022?\n\007cont" +
      "ent\030\003 \001(\0132\035.coreapi.model.MessageContent" +
      "B\006\272H\003\310\001\001R\007content\022\212\001\n\010bot_name\030\004 \001(\tBo\272H" +
      "l\272\001Y\n\rstring.maxLen\022(value must be no mo" +
      "re than 30 characters\032\036this == \'\' || siz" +
      "e(this) <= 30r\0162\014^[^@#$%:/]+$R\007botName\022\035" +
      "\n\nrequest_id\030\005 \001(\tR\trequestId\"O\n\033CreateU" +
      "serChatMessageResult\0220\n\007message\030\001 \001(\0132\026." +
      "coreapi.model.MessageR\007messageBf\n(io.cha" +
      "nnel.api.proto.pub.coreapi.serviceP\001Z8gi" +
      "thub.com/channel-io/ch-proto-public/core" +
      "api/go/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          io.channel.api.proto.pub.coreapi.common.SortOrderOuterClass.getDescriptor(),
          io.channel.api.proto.pub.coreapi.model.MessageOuterClass.getDescriptor(),
          io.channel.api.proto.pub.coreapi.model.MessageContentOuterClass.getDescriptor(),
          io.channel.api.proto.pub.coreapi.model.UserChatOuterClass.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_coreapi_service_SearchUserChatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_service_SearchUserChatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatsRequest_descriptor,
        new java.lang.String[] { "ChannelId", "State", "SortOrder", "Cursor", "Limit", });
    internal_static_coreapi_service_SearchUserChatsResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coreapi_service_SearchUserChatsResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatsResult_descriptor,
        new java.lang.String[] { "UserChats", "NextCursor", "HasNext", });
    internal_static_coreapi_service_SearchUserChatsForUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_coreapi_service_SearchUserChatsForUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatsForUserRequest_descriptor,
        new java.lang.String[] { "ChannelId", "UserId", "SortOrder", "Cursor", "Limit", });
    internal_static_coreapi_service_SearchUserChatsForUserResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_coreapi_service_SearchUserChatsForUserResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatsForUserResult_descriptor,
        new java.lang.String[] { "UserChats", "NextCursor", "HasNext", });
    internal_static_coreapi_service_GetUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_coreapi_service_GetUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_GetUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", });
    internal_static_coreapi_service_GetUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_coreapi_service_GetUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_GetUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_CreateUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_coreapi_service_CreateUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CreateUserChatRequest_descriptor,
        new java.lang.String[] { "ChannelId", "UserId", });
    internal_static_coreapi_service_CreateUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_coreapi_service_CreateUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CreateUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_UpdateUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_coreapi_service_UpdateUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_UpdateUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "Description", });
    internal_static_coreapi_service_UpdateUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_coreapi_service_UpdateUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_UpdateUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_DeleteUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_coreapi_service_DeleteUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_DeleteUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", });
    internal_static_coreapi_service_DeleteUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_coreapi_service_DeleteUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_DeleteUserChatResult_descriptor,
        new java.lang.String[] { });
    internal_static_coreapi_service_OpenUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_coreapi_service_OpenUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_OpenUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "BotName", });
    internal_static_coreapi_service_OpenUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_coreapi_service_OpenUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_OpenUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_CloseUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_coreapi_service_CloseUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CloseUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "BotName", });
    internal_static_coreapi_service_CloseUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_coreapi_service_CloseUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CloseUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_SnoozeUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_coreapi_service_SnoozeUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SnoozeUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "BotName", "Duration", });
    internal_static_coreapi_service_SnoozeUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_coreapi_service_SnoozeUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SnoozeUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_InviteManagersToUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_coreapi_service_InviteManagersToUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_InviteManagersToUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "BotName", "ManagerIds", });
    internal_static_coreapi_service_InviteManagersToUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_coreapi_service_InviteManagersToUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_InviteManagersToUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_AssignManagerToUserChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_coreapi_service_AssignManagerToUserChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_AssignManagerToUserChatRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "BotName", "ManagerId", });
    internal_static_coreapi_service_AssignManagerToUserChatResult_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_coreapi_service_AssignManagerToUserChatResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_AssignManagerToUserChatResult_descriptor,
        new java.lang.String[] { "UserChat", });
    internal_static_coreapi_service_SearchUserChatMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_coreapi_service_SearchUserChatMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatMessagesRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "SortOrder", "Cursor", "Limit", });
    internal_static_coreapi_service_SearchUserChatMessagesResult_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_coreapi_service_SearchUserChatMessagesResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_SearchUserChatMessagesResult_descriptor,
        new java.lang.String[] { "Messages", "NextCursor", "HasNext", });
    internal_static_coreapi_service_CreateUserChatMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_coreapi_service_CreateUserChatMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CreateUserChatMessageRequest_descriptor,
        new java.lang.String[] { "UserChatId", "ChannelId", "Content", "BotName", "RequestId", });
    internal_static_coreapi_service_CreateUserChatMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_coreapi_service_CreateUserChatMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_service_CreateUserChatMessageResult_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    io.channel.api.proto.pub.coreapi.common.SortOrderOuterClass.getDescriptor();
    io.channel.api.proto.pub.coreapi.model.MessageOuterClass.getDescriptor();
    io.channel.api.proto.pub.coreapi.model.MessageContentOuterClass.getDescriptor();
    io.channel.api.proto.pub.coreapi.model.UserChatOuterClass.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
