// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/campaign.proto

package io.channel.api.proto.pub.coreapi.model;

public interface CampaignOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.Campaign)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique campaign identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique campaign identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Channel ID this campaign belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <pre>
   * Channel ID this campaign belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <pre>
   * Display name of the campaign.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=128
   * </pre>
   *
   * <code>string name = 3 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Display name of the campaign.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=128
   * </pre>
   *
   * <code>string name = 3 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Current lifecycle state.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.CampaignState state = 4 [json_name = "state", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * Current lifecycle state.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.CampaignState state = 4 [json_name = "state", (.buf.validate.field) = { ... }</code>
   * @return The state.
   */
  io.channel.api.proto.pub.coreapi.model.CampaignState getState();

  /**
   * <pre>
   * Delivery medium type.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.MediumType medium_type = 5 [json_name = "mediumType"];</code>
   * @return The enum numeric value on the wire for mediumType.
   */
  int getMediumTypeValue();
  /**
   * <pre>
   * Delivery medium type.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.MediumType medium_type = 5 [json_name = "mediumType"];</code>
   * @return The mediumType.
   */
  io.channel.api.proto.pub.coreapi.model.MediumType getMediumType();

  /**
   * <pre>
   * Identifier of the specific medium instance.
   * Required for APP medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_id = 6 [json_name = "mediumId"];</code>
   * @return The mediumId.
   */
  java.lang.String getMediumId();
  /**
   * <pre>
   * Identifier of the specific medium instance.
   * Required for APP medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_id = 6 [json_name = "mediumId"];</code>
   * @return The bytes for mediumId.
   */
  com.google.protobuf.ByteString
      getMediumIdBytes();

  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 7 [json_name = "userQuery"];</code>
   * @return Whether the userQuery field is set.
   */
  boolean hasUserQuery();
  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 7 [json_name = "userQuery"];</code>
   * @return The userQuery.
   */
  com.google.protobuf.Struct getUserQuery();
  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 7 [json_name = "userQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getUserQueryOrBuilder();

  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 8 [json_name = "appSegments"];</code>
   */
  java.util.List<io.channel.api.proto.pub.coreapi.model.AppSegment> 
      getAppSegmentsList();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 8 [json_name = "appSegments"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.AppSegment getAppSegments(int index);
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 8 [json_name = "appSegments"];</code>
   */
  int getAppSegmentsCount();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 8 [json_name = "appSegments"];</code>
   */
  java.util.List<? extends io.channel.api.proto.pub.coreapi.model.AppSegmentOrBuilder> 
      getAppSegmentsOrBuilderList();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 8 [json_name = "appSegments"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.AppSegmentOrBuilder getAppSegmentsOrBuilder(
      int index);

  /**
   * <pre>
   * Name of the event that triggers the campaign.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string trigger_event_name = 9 [json_name = "triggerEventName"];</code>
   * @return The triggerEventName.
   */
  java.lang.String getTriggerEventName();
  /**
   * <pre>
   * Name of the event that triggers the campaign.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string trigger_event_name = 9 [json_name = "triggerEventName"];</code>
   * @return The bytes for triggerEventName.
   */
  com.google.protobuf.ByteString
      getTriggerEventNameBytes();

  /**
   * <pre>
   * Filtering query for the trigger event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct trigger_event_query = 10 [json_name = "triggerEventQuery"];</code>
   * @return Whether the triggerEventQuery field is set.
   */
  boolean hasTriggerEventQuery();
  /**
   * <pre>
   * Filtering query for the trigger event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct trigger_event_query = 10 [json_name = "triggerEventQuery"];</code>
   * @return The triggerEventQuery.
   */
  com.google.protobuf.Struct getTriggerEventQuery();
  /**
   * <pre>
   * Filtering query for the trigger event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct trigger_event_query = 10 [json_name = "triggerEventQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getTriggerEventQueryOrBuilder();

  /**
   * <pre>
   * Delay between trigger event and message delivery.
   * Maximum 90 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration waiting_time = 11 [json_name = "waitingTime", (.buf.validate.field) = { ... }</code>
   * @return Whether the waitingTime field is set.
   */
  boolean hasWaitingTime();
  /**
   * <pre>
   * Delay between trigger event and message delivery.
   * Maximum 90 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration waiting_time = 11 [json_name = "waitingTime", (.buf.validate.field) = { ... }</code>
   * @return The waitingTime.
   */
  com.google.protobuf.Duration getWaitingTime();
  /**
   * <pre>
   * Delay between trigger event and message delivery.
   * Maximum 90 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration waiting_time = 11 [json_name = "waitingTime", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.DurationOrBuilder getWaitingTimeOrBuilder();

  /**
   * <pre>
   * Name of the additional filter event.
   * When set, waiting_time must be non-zero.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string filter_event_name = 12 [json_name = "filterEventName"];</code>
   * @return The filterEventName.
   */
  java.lang.String getFilterEventName();
  /**
   * <pre>
   * Name of the additional filter event.
   * When set, waiting_time must be non-zero.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string filter_event_name = 12 [json_name = "filterEventName"];</code>
   * @return The bytes for filterEventName.
   */
  com.google.protobuf.ByteString
      getFilterEventNameBytes();

  /**
   * <pre>
   * Filtering query for the additional filter event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct filter_event_query = 13 [json_name = "filterEventQuery"];</code>
   * @return Whether the filterEventQuery field is set.
   */
  boolean hasFilterEventQuery();
  /**
   * <pre>
   * Filtering query for the additional filter event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct filter_event_query = 13 [json_name = "filterEventQuery"];</code>
   * @return The filterEventQuery.
   */
  com.google.protobuf.Struct getFilterEventQuery();
  /**
   * <pre>
   * Filtering query for the additional filter event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct filter_event_query = 13 [json_name = "filterEventQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getFilterEventQueryOrBuilder();

  /**
   * <pre>
   * Match logic for the additional event filter.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.CampaignFilterMatch filter_match = 14 [json_name = "filterMatch"];</code>
   * @return The enum numeric value on the wire for filterMatch.
   */
  int getFilterMatchValue();
  /**
   * <pre>
   * Match logic for the additional event filter.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.CampaignFilterMatch filter_match = 14 [json_name = "filterMatch"];</code>
   * @return The filterMatch.
   */
  io.channel.api.proto.pub.coreapi.model.CampaignFilterMatch getFilterMatch();

  /**
   * <pre>
   * Holding property constant for the additional event filter.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant filter_hpc = 15 [json_name = "filterHpc"];</code>
   * @return Whether the filterHpc field is set.
   */
  boolean hasFilterHpc();
  /**
   * <pre>
   * Holding property constant for the additional event filter.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant filter_hpc = 15 [json_name = "filterHpc"];</code>
   * @return The filterHpc.
   */
  io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant getFilterHpc();
  /**
   * <pre>
   * Holding property constant for the additional event filter.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant filter_hpc = 15 [json_name = "filterHpc"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstantOrBuilder getFilterHpcOrBuilder();

  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 16 [json_name = "conversionWindows"];</code>
   */
  int getConversionWindowsCount();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 16 [json_name = "conversionWindows"];</code>
   */
  boolean containsConversionWindows(
      java.lang.String key);
  /**
   * Use {@link #getConversionWindowsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Duration>
  getConversionWindows();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 16 [json_name = "conversionWindows"];</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Duration>
  getConversionWindowsMap();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 16 [json_name = "conversionWindows"];</code>
   */

  com.google.protobuf.Duration getConversionWindowsOrDefault(
      java.lang.String key,
      com.google.protobuf.Duration defaultValue);
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 16 [json_name = "conversionWindows"];</code>
   */

  com.google.protobuf.Duration getConversionWindowsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Name of the event tracked as a conversion goal.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string goal_event_name = 17 [json_name = "goalEventName"];</code>
   * @return The goalEventName.
   */
  java.lang.String getGoalEventName();
  /**
   * <pre>
   * Name of the event tracked as a conversion goal.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string goal_event_name = 17 [json_name = "goalEventName"];</code>
   * @return The bytes for goalEventName.
   */
  com.google.protobuf.ByteString
      getGoalEventNameBytes();

  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 18 [json_name = "goalEventQuery"];</code>
   * @return Whether the goalEventQuery field is set.
   */
  boolean hasGoalEventQuery();
  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 18 [json_name = "goalEventQuery"];</code>
   * @return The goalEventQuery.
   */
  com.google.protobuf.Struct getGoalEventQuery();
  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 18 [json_name = "goalEventQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getGoalEventQueryOrBuilder();

  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 19 [json_name = "goalEventDuration", (.buf.validate.field) = { ... }</code>
   * @return Whether the goalEventDuration field is set.
   */
  boolean hasGoalEventDuration();
  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 19 [json_name = "goalEventDuration", (.buf.validate.field) = { ... }</code>
   * @return The goalEventDuration.
   */
  com.google.protobuf.Duration getGoalEventDuration();
  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 19 [json_name = "goalEventDuration", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.DurationOrBuilder getGoalEventDurationOrBuilder();

  /**
   * <pre>
   * Holding property constant for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant goal_hpc = 20 [json_name = "goalHpc"];</code>
   * @return Whether the goalHpc field is set.
   */
  boolean hasGoalHpc();
  /**
   * <pre>
   * Holding property constant for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant goal_hpc = 20 [json_name = "goalHpc"];</code>
   * @return The goalHpc.
   */
  io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant getGoalHpc();
  /**
   * <pre>
   * Holding property constant for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.HoldingPropertyConstant goal_hpc = 20 [json_name = "goalHpc"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstantOrBuilder getGoalHpcOrBuilder();

  /**
   * <pre>
   * Whether this campaign contains advertising content.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool advertising = 21 [json_name = "advertising"];</code>
   * @return The advertising.
   */
  boolean getAdvertising();

  /**
   * <pre>
   * Whether to send via XMS (SMS/LMS/MMS) to offline users.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool send_to_offline_xms = 22 [json_name = "sendToOfflineXms"];</code>
   * @return The sendToOfflineXms.
   */
  boolean getSendToOfflineXms();

  /**
   * <pre>
   * Whether to send via email to offline users.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool send_to_offline_email = 23 [json_name = "sendToOfflineEmail"];</code>
   * @return The sendToOfflineEmail.
   */
  boolean getSendToOfflineEmail();

  /**
   * <pre>
   * Minimum interval between consecutive sends to the same user.
   * Valid range is 0 to 30 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration cooldown = 24 [json_name = "cooldown", (.buf.validate.field) = { ... }</code>
   * @return Whether the cooldown field is set.
   */
  boolean hasCooldown();
  /**
   * <pre>
   * Minimum interval between consecutive sends to the same user.
   * Valid range is 0 to 30 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration cooldown = 24 [json_name = "cooldown", (.buf.validate.field) = { ... }</code>
   * @return The cooldown.
   */
  com.google.protobuf.Duration getCooldown();
  /**
   * <pre>
   * Minimum interval between consecutive sends to the same user.
   * Valid range is 0 to 30 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration cooldown = 24 [json_name = "cooldown", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.DurationOrBuilder getCooldownOrBuilder();

  /**
   * <pre>
   * Send timing mode that determines when messages are delivered.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.CampaignSendMode send_mode = 25 [json_name = "sendMode"];</code>
   * @return The enum numeric value on the wire for sendMode.
   */
  int getSendModeValue();
  /**
   * <pre>
   * Send timing mode that determines when messages are delivered.
   * May be unset for draft campaigns.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.CampaignSendMode send_mode = 25 [json_name = "sendMode"];</code>
   * @return The sendMode.
   */
  io.channel.api.proto.pub.coreapi.model.CampaignSendMode getSendMode();

  /**
   * <pre>
   * Channel operation ID for business hours scheduling.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string channel_operation_id = 26 [json_name = "channelOperationId"];</code>
   * @return The channelOperationId.
   */
  java.lang.String getChannelOperationId();
  /**
   * <pre>
   * Channel operation ID for business hours scheduling.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string channel_operation_id = 26 [json_name = "channelOperationId"];</code>
   * @return The bytes for channelOperationId.
   */
  com.google.protobuf.ByteString
      getChannelOperationIdBytes();

  /**
   * <pre>
   * Custom time ranges for message delivery.
   * Applicable when send_mode is CUSTOM_USING_SENDER_TIME or CUSTOM_USING_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange send_time_ranges = 27 [json_name = "sendTimeRanges"];</code>
   */
  java.util.List<io.channel.api.proto.pub.coreapi.model.TimeRange> 
      getSendTimeRangesList();
  /**
   * <pre>
   * Custom time ranges for message delivery.
   * Applicable when send_mode is CUSTOM_USING_SENDER_TIME or CUSTOM_USING_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange send_time_ranges = 27 [json_name = "sendTimeRanges"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.TimeRange getSendTimeRanges(int index);
  /**
   * <pre>
   * Custom time ranges for message delivery.
   * Applicable when send_mode is CUSTOM_USING_SENDER_TIME or CUSTOM_USING_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange send_time_ranges = 27 [json_name = "sendTimeRanges"];</code>
   */
  int getSendTimeRangesCount();
  /**
   * <pre>
   * Custom time ranges for message delivery.
   * Applicable when send_mode is CUSTOM_USING_SENDER_TIME or CUSTOM_USING_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange send_time_ranges = 27 [json_name = "sendTimeRanges"];</code>
   */
  java.util.List<? extends io.channel.api.proto.pub.coreapi.model.TimeRangeOrBuilder> 
      getSendTimeRangesOrBuilderList();
  /**
   * <pre>
   * Custom time ranges for message delivery.
   * Applicable when send_mode is CUSTOM_USING_SENDER_TIME or CUSTOM_USING_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange send_time_ranges = 27 [json_name = "sendTimeRanges"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.TimeRangeOrBuilder getSendTimeRangesOrBuilder(
      int index);

  /**
   * <pre>
   * Campaign start time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 28 [json_name = "startAt"];</code>
   * @return Whether the startAt field is set.
   */
  boolean hasStartAt();
  /**
   * <pre>
   * Campaign start time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 28 [json_name = "startAt"];</code>
   * @return The startAt.
   */
  com.google.protobuf.Timestamp getStartAt();
  /**
   * <pre>
   * Campaign start time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 28 [json_name = "startAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartAtOrBuilder();

  /**
   * <pre>
   * Scheduled campaign end timestamp.
   * Campaign automatically stops after this time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_at = 29 [json_name = "endAt"];</code>
   * @return Whether the endAt field is set.
   */
  boolean hasEndAt();
  /**
   * <pre>
   * Scheduled campaign end timestamp.
   * Campaign automatically stops after this time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_at = 29 [json_name = "endAt"];</code>
   * @return The endAt.
   */
  com.google.protobuf.Timestamp getEndAt();
  /**
   * <pre>
   * Scheduled campaign end timestamp.
   * Campaign automatically stops after this time.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_at = 29 [json_name = "endAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndAtOrBuilder();

  /**
   * <pre>
   * Draft snapshot of the campaign saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 30 [json_name = "draft"];</code>
   * @return Whether the draft field is set.
   */
  boolean hasDraft();
  /**
   * <pre>
   * Draft snapshot of the campaign saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 30 [json_name = "draft"];</code>
   * @return The draft.
   */
  com.google.protobuf.Struct getDraft();
  /**
   * <pre>
   * Draft snapshot of the campaign saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 30 [json_name = "draft"];</code>
   */
  com.google.protobuf.StructOrBuilder getDraftOrBuilder();

  /**
   * <pre>
   * Campaign creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 31 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Campaign creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 31 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Campaign creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 31 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Campaign last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <pre>
   * Campaign last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <pre>
   * Campaign last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <pre>
   * Total number of messages sent.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 sent = 33 [json_name = "sent"];</code>
   * @return The sent.
   */
  int getSent();

  /**
   * <pre>
   * Total number of message views.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 view = 34 [json_name = "view"];</code>
   * @return The view.
   */
  int getView();

  /**
   * <pre>
   * Total number of goal conversions achieved.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 goal = 35 [json_name = "goal"];</code>
   * @return The goal.
   */
  int getGoal();

  /**
   * <pre>
   * Total number of message link clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 click = 36 [json_name = "click"];</code>
   * @return The click.
   */
  int getClick();
}
