// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/campaign.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * HoldingPropertyConstant enables dynamic property-based filtering
 * by holding a constant value from a base event for use in event queries.
 * </pre>
 *
 * Protobuf type {@code coreapi.model.HoldingPropertyConstant}
 */
public final class HoldingPropertyConstant extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.model.HoldingPropertyConstant)
    HoldingPropertyConstantOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HoldingPropertyConstant.newBuilder() to construct.
  private HoldingPropertyConstant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HoldingPropertyConstant() {
    baseEventName_ = "";
    baseEventKey_ = "";
    baseEventType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HoldingPropertyConstant();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HoldingPropertyConstant(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            baseEventName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            baseEventKey_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (eventQuery_ != null) {
              subBuilder = eventQuery_.toBuilder();
            }
            eventQuery_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eventQuery_);
              eventQuery_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            baseEventType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.CampaignOuterClass.internal_static_coreapi_model_HoldingPropertyConstant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.model.CampaignOuterClass.internal_static_coreapi_model_HoldingPropertyConstant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.class, io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.Builder.class);
  }

  public static final int BASE_EVENT_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object baseEventName_;
  /**
   * <pre>
   * Name of the base event to extract the property value from.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
   * @return The baseEventName.
   */
  @java.lang.Override
  public java.lang.String getBaseEventName() {
    java.lang.Object ref = baseEventName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseEventName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the base event to extract the property value from.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for baseEventName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseEventNameBytes() {
    java.lang.Object ref = baseEventName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseEventName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_EVENT_KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object baseEventKey_;
  /**
   * <pre>
   * Property key to extract from the base event.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
   * @return The baseEventKey.
   */
  @java.lang.Override
  public java.lang.String getBaseEventKey() {
    java.lang.Object ref = baseEventKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseEventKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Property key to extract from the base event.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
   * @return The bytes for baseEventKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseEventKeyBytes() {
    java.lang.Object ref = baseEventKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseEventKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_QUERY_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct eventQuery_;
  /**
   * <pre>
   * Query expression for matching the held property value.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
   * @return Whether the eventQuery field is set.
   */
  @java.lang.Override
  public boolean hasEventQuery() {
    return eventQuery_ != null;
  }
  /**
   * <pre>
   * Query expression for matching the held property value.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
   * @return The eventQuery.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getEventQuery() {
    return eventQuery_ == null ? com.google.protobuf.Struct.getDefaultInstance() : eventQuery_;
  }
  /**
   * <pre>
   * Query expression for matching the held property value.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getEventQueryOrBuilder() {
    return getEventQuery();
  }

  public static final int BASE_EVENT_TYPE_FIELD_NUMBER = 4;
  private int baseEventType_;
  /**
   * <pre>
   * Type of base event this holding property constant is associated with.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for baseEventType.
   */
  @java.lang.Override public int getBaseEventTypeValue() {
    return baseEventType_;
  }
  /**
   * <pre>
   * Type of base event this holding property constant is associated with.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
   * @return The baseEventType.
   */
  @java.lang.Override public io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType getBaseEventType() {
    @SuppressWarnings("deprecation")
    io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType result = io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.valueOf(baseEventType_);
    return result == null ? io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseEventName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, baseEventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseEventKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, baseEventKey_);
    }
    if (eventQuery_ != null) {
      output.writeMessage(3, getEventQuery());
    }
    if (baseEventType_ != io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.CAMPAIGN_BASE_EVENT_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, baseEventType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseEventName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, baseEventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseEventKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, baseEventKey_);
    }
    if (eventQuery_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEventQuery());
    }
    if (baseEventType_ != io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.CAMPAIGN_BASE_EVENT_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, baseEventType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant other = (io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant) obj;

    if (!getBaseEventName()
        .equals(other.getBaseEventName())) return false;
    if (!getBaseEventKey()
        .equals(other.getBaseEventKey())) return false;
    if (hasEventQuery() != other.hasEventQuery()) return false;
    if (hasEventQuery()) {
      if (!getEventQuery()
          .equals(other.getEventQuery())) return false;
    }
    if (baseEventType_ != other.baseEventType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BASE_EVENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBaseEventName().hashCode();
    hash = (37 * hash) + BASE_EVENT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getBaseEventKey().hashCode();
    if (hasEventQuery()) {
      hash = (37 * hash) + EVENT_QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getEventQuery().hashCode();
    }
    hash = (37 * hash) + BASE_EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + baseEventType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * HoldingPropertyConstant enables dynamic property-based filtering
   * by holding a constant value from a base event for use in event queries.
   * </pre>
   *
   * Protobuf type {@code coreapi.model.HoldingPropertyConstant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.model.HoldingPropertyConstant)
      io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.CampaignOuterClass.internal_static_coreapi_model_HoldingPropertyConstant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.model.CampaignOuterClass.internal_static_coreapi_model_HoldingPropertyConstant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.class, io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      baseEventName_ = "";

      baseEventKey_ = "";

      if (eventQueryBuilder_ == null) {
        eventQuery_ = null;
      } else {
        eventQuery_ = null;
        eventQueryBuilder_ = null;
      }
      baseEventType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.model.CampaignOuterClass.internal_static_coreapi_model_HoldingPropertyConstant_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant build() {
      io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant buildPartial() {
      io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant result = new io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant(this);
      result.baseEventName_ = baseEventName_;
      result.baseEventKey_ = baseEventKey_;
      if (eventQueryBuilder_ == null) {
        result.eventQuery_ = eventQuery_;
      } else {
        result.eventQuery_ = eventQueryBuilder_.build();
      }
      result.baseEventType_ = baseEventType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant other) {
      if (other == io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant.getDefaultInstance()) return this;
      if (!other.getBaseEventName().isEmpty()) {
        baseEventName_ = other.baseEventName_;
        onChanged();
      }
      if (!other.getBaseEventKey().isEmpty()) {
        baseEventKey_ = other.baseEventKey_;
        onChanged();
      }
      if (other.hasEventQuery()) {
        mergeEventQuery(other.getEventQuery());
      }
      if (other.baseEventType_ != 0) {
        setBaseEventTypeValue(other.getBaseEventTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object baseEventName_ = "";
    /**
     * <pre>
     * Name of the base event to extract the property value from.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
     * @return The baseEventName.
     */
    public java.lang.String getBaseEventName() {
      java.lang.Object ref = baseEventName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseEventName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the base event to extract the property value from.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
     * @return The bytes for baseEventName.
     */
    public com.google.protobuf.ByteString
        getBaseEventNameBytes() {
      java.lang.Object ref = baseEventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseEventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the base event to extract the property value from.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
     * @param value The baseEventName to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      baseEventName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the base event to extract the property value from.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseEventName() {
      
      baseEventName_ = getDefaultInstance().getBaseEventName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the base event to extract the property value from.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_name = 1 [json_name = "baseEventName", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for baseEventName to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      baseEventName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object baseEventKey_ = "";
    /**
     * <pre>
     * Property key to extract from the base event.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
     * @return The baseEventKey.
     */
    public java.lang.String getBaseEventKey() {
      java.lang.Object ref = baseEventKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseEventKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Property key to extract from the base event.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
     * @return The bytes for baseEventKey.
     */
    public com.google.protobuf.ByteString
        getBaseEventKeyBytes() {
      java.lang.Object ref = baseEventKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseEventKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Property key to extract from the base event.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
     * @param value The baseEventKey to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      baseEventKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Property key to extract from the base event.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseEventKey() {
      
      baseEventKey_ = getDefaultInstance().getBaseEventKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Property key to extract from the base event.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string base_event_key = 2 [json_name = "baseEventKey", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for baseEventKey to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      baseEventKey_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct eventQuery_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> eventQueryBuilder_;
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     * @return Whether the eventQuery field is set.
     */
    public boolean hasEventQuery() {
      return eventQueryBuilder_ != null || eventQuery_ != null;
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     * @return The eventQuery.
     */
    public com.google.protobuf.Struct getEventQuery() {
      if (eventQueryBuilder_ == null) {
        return eventQuery_ == null ? com.google.protobuf.Struct.getDefaultInstance() : eventQuery_;
      } else {
        return eventQueryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public Builder setEventQuery(com.google.protobuf.Struct value) {
      if (eventQueryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventQuery_ = value;
        onChanged();
      } else {
        eventQueryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public Builder setEventQuery(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (eventQueryBuilder_ == null) {
        eventQuery_ = builderForValue.build();
        onChanged();
      } else {
        eventQueryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public Builder mergeEventQuery(com.google.protobuf.Struct value) {
      if (eventQueryBuilder_ == null) {
        if (eventQuery_ != null) {
          eventQuery_ =
            com.google.protobuf.Struct.newBuilder(eventQuery_).mergeFrom(value).buildPartial();
        } else {
          eventQuery_ = value;
        }
        onChanged();
      } else {
        eventQueryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public Builder clearEventQuery() {
      if (eventQueryBuilder_ == null) {
        eventQuery_ = null;
        onChanged();
      } else {
        eventQuery_ = null;
        eventQueryBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public com.google.protobuf.Struct.Builder getEventQueryBuilder() {
      
      onChanged();
      return getEventQueryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    public com.google.protobuf.StructOrBuilder getEventQueryOrBuilder() {
      if (eventQueryBuilder_ != null) {
        return eventQueryBuilder_.getMessageOrBuilder();
      } else {
        return eventQuery_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : eventQuery_;
      }
    }
    /**
     * <pre>
     * Query expression for matching the held property value.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Struct event_query = 3 [json_name = "eventQuery"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getEventQueryFieldBuilder() {
      if (eventQueryBuilder_ == null) {
        eventQueryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getEventQuery(),
                getParentForChildren(),
                isClean());
        eventQuery_ = null;
      }
      return eventQueryBuilder_;
    }

    private int baseEventType_ = 0;
    /**
     * <pre>
     * Type of base event this holding property constant is associated with.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for baseEventType.
     */
    @java.lang.Override public int getBaseEventTypeValue() {
      return baseEventType_;
    }
    /**
     * <pre>
     * Type of base event this holding property constant is associated with.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for baseEventType to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventTypeValue(int value) {
      
      baseEventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of base event this holding property constant is associated with.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
     * @return The baseEventType.
     */
    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType getBaseEventType() {
      @SuppressWarnings("deprecation")
      io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType result = io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.valueOf(baseEventType_);
      return result == null ? io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Type of base event this holding property constant is associated with.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
     * @param value The baseEventType to set.
     * @return This builder for chaining.
     */
    public Builder setBaseEventType(io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      baseEventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of base event this holding property constant is associated with.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.coreapi.model.CampaignBaseEventType base_event_type = 4 [json_name = "baseEventType", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseEventType() {
      
      baseEventType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The base_event_name to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBaseEventName(java.lang.String value) {
    	if (value == null)
    		return clearBaseEventName();
    	else
    		return setBaseEventName(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBaseEventName(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearBaseEventName();
    	else
    		return setBaseEventName(mapFunc.apply(value));
    }
    	
    /**
     * @param value The base_event_key to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBaseEventKey(java.lang.String value) {
    	if (value == null)
    		return clearBaseEventKey();
    	else
    		return setBaseEventKey(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBaseEventKey(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearBaseEventKey();
    	else
    		return setBaseEventKey(mapFunc.apply(value));
    }
    	
    /**
     * @param value The event_query to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearEventQuery(com.google.protobuf.Struct value) {
    	if (value == null)
    		return clearEventQuery();
    	else
    		return setEventQuery(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearEventQuery(T value, java.util.function.Function<T, com.google.protobuf.Struct> mapFunc) {
    	if (value == null)
    		return clearEventQuery();
    	else
    		return setEventQuery(mapFunc.apply(value));
    }
    	
    /**
     * @param value The base_event_type to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBaseEventType(io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType value) {
    	if (value == null)
    		return clearBaseEventType();
    	else
    		return setBaseEventType(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBaseEventType(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.CampaignBaseEventType> mapFunc) {
    	if (value == null)
    		return clearBaseEventType();
    	else
    		return setBaseEventType(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.model.HoldingPropertyConstant)
  }

  // @@protoc_insertion_point(class_scope:coreapi.model.HoldingPropertyConstant)
  private static final io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant();
  }

  public static io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HoldingPropertyConstant>
      PARSER = new com.google.protobuf.AbstractParser<HoldingPropertyConstant>() {
    @java.lang.Override
    public HoldingPropertyConstant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HoldingPropertyConstant(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HoldingPropertyConstant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HoldingPropertyConstant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.HoldingPropertyConstant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
