// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/message.proto

package io.channel.api.proto.pub.coreapi.model;

public interface MessageReactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.MessageReaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Emoji identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string emoji_name = 1 [json_name = "emojiName", (.buf.validate.field) = { ... }</code>
   * @return The emojiName.
   */
  java.lang.String getEmojiName();
  /**
   * <pre>
   * Emoji identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string emoji_name = 1 [json_name = "emojiName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for emojiName.
   */
  com.google.protobuf.ByteString
      getEmojiNameBytes();

  /**
   * <pre>
   * Ordered list of person keys who reacted with this emoji.
   * Each key is in the format "{personType}-{personId}".
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string person_keys = 2 [json_name = "personKeys"];</code>
   * @return A list containing the personKeys.
   */
  java.util.List<java.lang.String>
      getPersonKeysList();
  /**
   * <pre>
   * Ordered list of person keys who reacted with this emoji.
   * Each key is in the format "{personType}-{personId}".
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string person_keys = 2 [json_name = "personKeys"];</code>
   * @return The count of personKeys.
   */
  int getPersonKeysCount();
  /**
   * <pre>
   * Ordered list of person keys who reacted with this emoji.
   * Each key is in the format "{personType}-{personId}".
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string person_keys = 2 [json_name = "personKeys"];</code>
   * @param index The index of the element to return.
   * @return The personKeys at the given index.
   */
  java.lang.String getPersonKeys(int index);
  /**
   * <pre>
   * Ordered list of person keys who reacted with this emoji.
   * Each key is in the format "{personType}-{personId}".
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string person_keys = 2 [json_name = "personKeys"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the personKeys at the given index.
   */
  com.google.protobuf.ByteString
      getPersonKeysBytes(int index);
}
