// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/message.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * MessageThread represents thread metadata on a root message.
 * </pre>
 *
 * Protobuf type {@code coreapi.model.MessageThread}
 */
public final class MessageThread extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.model.MessageThread)
    MessageThreadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageThread.newBuilder() to construct.
  private MessageThread(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageThread() {
    id_ = "";
    managerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    repliedManagerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageThread();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageThread(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              managerIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            managerIds_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              repliedManagerIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            repliedManagerIds_.add(s);
            break;
          }
          case 32: {

            replyCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        managerIds_ = managerIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        repliedManagerIds_ = repliedManagerIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageThread_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageThread_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.model.MessageThread.class, io.channel.api.proto.pub.coreapi.model.MessageThread.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Unique thread identifier.
   * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique thread identifier.
   * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANAGER_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList managerIds_;
  /**
   * <pre>
   * Manager IDs assigned to this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
   * @return A list containing the managerIds.
   */
  public com.google.protobuf.ProtocolStringList
      getManagerIdsList() {
    return managerIds_;
  }
  /**
   * <pre>
   * Manager IDs assigned to this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
   * @return The count of managerIds.
   */
  public int getManagerIdsCount() {
    return managerIds_.size();
  }
  /**
   * <pre>
   * Manager IDs assigned to this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
   * @param index The index of the element to return.
   * @return The managerIds at the given index.
   */
  public java.lang.String getManagerIds(int index) {
    return managerIds_.get(index);
  }
  /**
   * <pre>
   * Manager IDs assigned to this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the managerIds at the given index.
   */
  public com.google.protobuf.ByteString
      getManagerIdsBytes(int index) {
    return managerIds_.getByteString(index);
  }

  public static final int REPLIED_MANAGER_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList repliedManagerIds_;
  /**
   * <pre>
   * Ordered list of manager IDs who have replied in this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
   * @return A list containing the repliedManagerIds.
   */
  public com.google.protobuf.ProtocolStringList
      getRepliedManagerIdsList() {
    return repliedManagerIds_;
  }
  /**
   * <pre>
   * Ordered list of manager IDs who have replied in this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
   * @return The count of repliedManagerIds.
   */
  public int getRepliedManagerIdsCount() {
    return repliedManagerIds_.size();
  }
  /**
   * <pre>
   * Ordered list of manager IDs who have replied in this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
   * @param index The index of the element to return.
   * @return The repliedManagerIds at the given index.
   */
  public java.lang.String getRepliedManagerIds(int index) {
    return repliedManagerIds_.get(index);
  }
  /**
   * <pre>
   * Ordered list of manager IDs who have replied in this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the repliedManagerIds at the given index.
   */
  public com.google.protobuf.ByteString
      getRepliedManagerIdsBytes(int index) {
    return repliedManagerIds_.getByteString(index);
  }

  public static final int REPLY_COUNT_FIELD_NUMBER = 4;
  private int replyCount_;
  /**
   * <pre>
   * Total number of replies in this thread.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 reply_count = 4 [json_name = "replyCount"];</code>
   * @return The replyCount.
   */
  @java.lang.Override
  public int getReplyCount() {
    return replyCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < managerIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, managerIds_.getRaw(i));
    }
    for (int i = 0; i < repliedManagerIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, repliedManagerIds_.getRaw(i));
    }
    if (replyCount_ != 0) {
      output.writeInt32(4, replyCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < managerIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(managerIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getManagerIdsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < repliedManagerIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(repliedManagerIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRepliedManagerIdsList().size();
    }
    if (replyCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, replyCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.model.MessageThread)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.model.MessageThread other = (io.channel.api.proto.pub.coreapi.model.MessageThread) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getManagerIdsList()
        .equals(other.getManagerIdsList())) return false;
    if (!getRepliedManagerIdsList()
        .equals(other.getRepliedManagerIdsList())) return false;
    if (getReplyCount()
        != other.getReplyCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getManagerIdsCount() > 0) {
      hash = (37 * hash) + MANAGER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getManagerIdsList().hashCode();
    }
    if (getRepliedManagerIdsCount() > 0) {
      hash = (37 * hash) + REPLIED_MANAGER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getRepliedManagerIdsList().hashCode();
    }
    hash = (37 * hash) + REPLY_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getReplyCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageThread parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.model.MessageThread prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MessageThread represents thread metadata on a root message.
   * </pre>
   *
   * Protobuf type {@code coreapi.model.MessageThread}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.model.MessageThread)
      io.channel.api.proto.pub.coreapi.model.MessageThreadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageThread_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageThread_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.model.MessageThread.class, io.channel.api.proto.pub.coreapi.model.MessageThread.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.model.MessageThread.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      managerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      repliedManagerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      replyCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageThread_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageThread getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.model.MessageThread.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageThread build() {
      io.channel.api.proto.pub.coreapi.model.MessageThread result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageThread buildPartial() {
      io.channel.api.proto.pub.coreapi.model.MessageThread result = new io.channel.api.proto.pub.coreapi.model.MessageThread(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (((bitField0_ & 0x00000001) != 0)) {
        managerIds_ = managerIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.managerIds_ = managerIds_;
      if (((bitField0_ & 0x00000002) != 0)) {
        repliedManagerIds_ = repliedManagerIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.repliedManagerIds_ = repliedManagerIds_;
      result.replyCount_ = replyCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.model.MessageThread) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.model.MessageThread)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.model.MessageThread other) {
      if (other == io.channel.api.proto.pub.coreapi.model.MessageThread.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.managerIds_.isEmpty()) {
        if (managerIds_.isEmpty()) {
          managerIds_ = other.managerIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureManagerIdsIsMutable();
          managerIds_.addAll(other.managerIds_);
        }
        onChanged();
      }
      if (!other.repliedManagerIds_.isEmpty()) {
        if (repliedManagerIds_.isEmpty()) {
          repliedManagerIds_ = other.repliedManagerIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRepliedManagerIdsIsMutable();
          repliedManagerIds_.addAll(other.repliedManagerIds_);
        }
        onChanged();
      }
      if (other.getReplyCount() != 0) {
        setReplyCount(other.getReplyCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.model.MessageThread parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.model.MessageThread) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique thread identifier.
     * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique thread identifier.
     * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique thread identifier.
     * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique thread identifier.
     * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique thread identifier.
     * Composite key in the format "{chatType}-{chatId}-{rootMessageId}".
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList managerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureManagerIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        managerIds_ = new com.google.protobuf.LazyStringArrayList(managerIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @return A list containing the managerIds.
     */
    public com.google.protobuf.ProtocolStringList
        getManagerIdsList() {
      return managerIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @return The count of managerIds.
     */
    public int getManagerIdsCount() {
      return managerIds_.size();
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param index The index of the element to return.
     * @return The managerIds at the given index.
     */
    public java.lang.String getManagerIds(int index) {
      return managerIds_.get(index);
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the managerIds at the given index.
     */
    public com.google.protobuf.ByteString
        getManagerIdsBytes(int index) {
      return managerIds_.getByteString(index);
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param index The index to set the value at.
     * @param value The managerIds to set.
     * @return This builder for chaining.
     */
    public Builder setManagerIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManagerIdsIsMutable();
      managerIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param value The managerIds to add.
     * @return This builder for chaining.
     */
    public Builder addManagerIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManagerIdsIsMutable();
      managerIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param values The managerIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllManagerIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureManagerIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, managerIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearManagerIds() {
      managerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manager IDs assigned to this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string manager_ids = 2 [json_name = "managerIds"];</code>
     * @param value The bytes of the managerIds to add.
     * @return This builder for chaining.
     */
    public Builder addManagerIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureManagerIdsIsMutable();
      managerIds_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList repliedManagerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRepliedManagerIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        repliedManagerIds_ = new com.google.protobuf.LazyStringArrayList(repliedManagerIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @return A list containing the repliedManagerIds.
     */
    public com.google.protobuf.ProtocolStringList
        getRepliedManagerIdsList() {
      return repliedManagerIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @return The count of repliedManagerIds.
     */
    public int getRepliedManagerIdsCount() {
      return repliedManagerIds_.size();
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param index The index of the element to return.
     * @return The repliedManagerIds at the given index.
     */
    public java.lang.String getRepliedManagerIds(int index) {
      return repliedManagerIds_.get(index);
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the repliedManagerIds at the given index.
     */
    public com.google.protobuf.ByteString
        getRepliedManagerIdsBytes(int index) {
      return repliedManagerIds_.getByteString(index);
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param index The index to set the value at.
     * @param value The repliedManagerIds to set.
     * @return This builder for chaining.
     */
    public Builder setRepliedManagerIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepliedManagerIdsIsMutable();
      repliedManagerIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param value The repliedManagerIds to add.
     * @return This builder for chaining.
     */
    public Builder addRepliedManagerIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepliedManagerIdsIsMutable();
      repliedManagerIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param values The repliedManagerIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRepliedManagerIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureRepliedManagerIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, repliedManagerIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepliedManagerIds() {
      repliedManagerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of manager IDs who have replied in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated string replied_manager_ids = 3 [json_name = "repliedManagerIds"];</code>
     * @param value The bytes of the repliedManagerIds to add.
     * @return This builder for chaining.
     */
    public Builder addRepliedManagerIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRepliedManagerIdsIsMutable();
      repliedManagerIds_.add(value);
      onChanged();
      return this;
    }

    private int replyCount_ ;
    /**
     * <pre>
     * Total number of replies in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>int32 reply_count = 4 [json_name = "replyCount"];</code>
     * @return The replyCount.
     */
    @java.lang.Override
    public int getReplyCount() {
      return replyCount_;
    }
    /**
     * <pre>
     * Total number of replies in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>int32 reply_count = 4 [json_name = "replyCount"];</code>
     * @param value The replyCount to set.
     * @return This builder for chaining.
     */
    public Builder setReplyCount(int value) {
      
      replyCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total number of replies in this thread.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>int32 reply_count = 4 [json_name = "replyCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyCount() {
      
      replyCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearId(java.lang.String value) {
    	if (value == null)
    		return clearId();
    	else
    		return setId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearId();
    	else
    		return setId(mapFunc.apply(value));
    }
    	
    /**
     * @param values The manager_ids to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrClearManagerIds(java.lang.Iterable<java.lang.String> values) {
    	if (values == null)
    		return clearManagerIds();
    	else
    		return addAllManagerIds(values);
    }
    	
    /**
     * @param values The values to map.
     * @param mapFunc The function to map the values into each proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapAllOrClearManagerIds(java.lang.Iterable<T> values, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (values == null)
    		return clearManagerIds();
    	else {
    		values.forEach(value -> addManagerIds(mapFunc.apply(value)));
    		return this;
    	}
    }
    	
    /**
     * @param values The replied_manager_ids to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrClearRepliedManagerIds(java.lang.Iterable<java.lang.String> values) {
    	if (values == null)
    		return clearRepliedManagerIds();
    	else
    		return addAllRepliedManagerIds(values);
    }
    	
    /**
     * @param values The values to map.
     * @param mapFunc The function to map the values into each proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapAllOrClearRepliedManagerIds(java.lang.Iterable<T> values, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (values == null)
    		return clearRepliedManagerIds();
    	else {
    		values.forEach(value -> addRepliedManagerIds(mapFunc.apply(value)));
    		return this;
    	}
    }
    	
    /**
     * @param value The reply_count to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearReplyCount(java.lang.Integer value) {
    	if (value == null)
    		return clearReplyCount();
    	else
    		return setReplyCount(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearReplyCount(T value, java.util.function.Function<T, java.lang.Integer> mapFunc) {
    	if (value == null)
    		return clearReplyCount();
    	else
    		return setReplyCount(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.model.MessageThread)
  }

  // @@protoc_insertion_point(class_scope:coreapi.model.MessageThread)
  private static final io.channel.api.proto.pub.coreapi.model.MessageThread DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.model.MessageThread();
  }

  public static io.channel.api.proto.pub.coreapi.model.MessageThread getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageThread>
      PARSER = new com.google.protobuf.AbstractParser<MessageThread>() {
    @java.lang.Override
    public MessageThread parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageThread(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageThread> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageThread> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageThread getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
