// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/online.proto

package io.channel.api.proto.pub.coreapi.model;

public interface OnlineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.Online)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Channel ID this online record belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <pre>
   * Channel ID this online record belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <pre>
   * Type of the person (e.g., manager, user).
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string person_type = 2 [json_name = "personType", (.buf.validate.field) = { ... }</code>
   * @return The personType.
   */
  java.lang.String getPersonType();
  /**
   * <pre>
   * Type of the person (e.g., manager, user).
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string person_type = 2 [json_name = "personType", (.buf.validate.field) = { ... }</code>
   * @return The bytes for personType.
   */
  com.google.protobuf.ByteString
      getPersonTypeBytes();

  /**
   * <pre>
   * Identifier of the person.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string person_id = 3 [json_name = "personId", (.buf.validate.field) = { ... }</code>
   * @return The personId.
   */
  java.lang.String getPersonId();
  /**
   * <pre>
   * Identifier of the person.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string person_id = 3 [json_name = "personId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for personId.
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();
}
