// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/operator_status.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * OperatorStatus represents the operational status of a manager.
 * </pre>
 *
 * Protobuf type {@code coreapi.model.OperatorStatus}
 */
public final class OperatorStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.model.OperatorStatus)
    OperatorStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OperatorStatus.newBuilder() to construct.
  private OperatorStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OperatorStatus() {
    id_ = "";
    managerId_ = "";
    channelId_ = "";
    operatorStatusType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OperatorStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OperatorStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            managerId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            channelId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            operatorStatusType_ = rawValue;
            break;
          }
          case 40: {

            enable_ = input.readBool();
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (updatedAt_ != null) {
              subBuilder = updatedAt_.toBuilder();
            }
            updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updatedAt_);
              updatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (typeUpdatedAt_ != null) {
              subBuilder = typeUpdatedAt_.toBuilder();
            }
            typeUpdatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(typeUpdatedAt_);
              typeUpdatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.OperatorStatusOuterClass.internal_static_coreapi_model_OperatorStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.model.OperatorStatusOuterClass.internal_static_coreapi_model_OperatorStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.model.OperatorStatus.class, io.channel.api.proto.pub.coreapi.model.OperatorStatus.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Unique operator status identifier.
   * Same as the manager ID.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique operator status identifier.
   * Same as the manager ID.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANAGER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object managerId_;
  /**
   * <pre>
   * ID of the manager this status belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
   * @return The managerId.
   */
  @java.lang.Override
  public java.lang.String getManagerId() {
    java.lang.Object ref = managerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      managerId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the manager this status belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for managerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManagerIdBytes() {
    java.lang.Object ref = managerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      managerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object channelId_;
  /**
   * <pre>
   * Channel ID this operator status belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Channel ID this operator status belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATOR_STATUS_TYPE_FIELD_NUMBER = 4;
  private int operatorStatusType_;
  /**
   * <pre>
   * Current activity type of the operator.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
   * @return The enum numeric value on the wire for operatorStatusType.
   */
  @java.lang.Override public int getOperatorStatusTypeValue() {
    return operatorStatusType_;
  }
  /**
   * <pre>
   * Current activity type of the operator.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
   * @return The operatorStatusType.
   */
  @java.lang.Override public io.channel.api.proto.pub.coreapi.model.OperatorStatusType getOperatorStatusType() {
    @SuppressWarnings("deprecation")
    io.channel.api.proto.pub.coreapi.model.OperatorStatusType result = io.channel.api.proto.pub.coreapi.model.OperatorStatusType.valueOf(operatorStatusType_);
    return result == null ? io.channel.api.proto.pub.coreapi.model.OperatorStatusType.UNRECOGNIZED : result;
  }

  public static final int ENABLE_FIELD_NUMBER = 5;
  private boolean enable_;
  /**
   * <pre>
   * Whether the operator is enabled for assignment.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool enable = 5 [json_name = "enable"];</code>
   * @return The enable.
   */
  @java.lang.Override
  public boolean getEnable() {
    return enable_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <pre>
   * Operator status creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <pre>
   * Operator status creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <pre>
   * Operator status creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <pre>
   * Operator status last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return updatedAt_ != null;
  }
  /**
   * <pre>
   * Operator status last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <pre>
   * Operator status last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return getUpdatedAt();
  }

  public static final int TYPE_UPDATED_AT_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp typeUpdatedAt_;
  /**
   * <pre>
   * Timestamp when the operator status type was last changed.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
   * @return Whether the typeUpdatedAt field is set.
   */
  @java.lang.Override
  public boolean hasTypeUpdatedAt() {
    return typeUpdatedAt_ != null;
  }
  /**
   * <pre>
   * Timestamp when the operator status type was last changed.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
   * @return The typeUpdatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTypeUpdatedAt() {
    return typeUpdatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : typeUpdatedAt_;
  }
  /**
   * <pre>
   * Timestamp when the operator status type was last changed.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTypeUpdatedAtOrBuilder() {
    return getTypeUpdatedAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(managerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, managerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, channelId_);
    }
    if (operatorStatusType_ != io.channel.api.proto.pub.coreapi.model.OperatorStatusType.OPERATOR_STATUS_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, operatorStatusType_);
    }
    if (enable_ != false) {
      output.writeBool(5, enable_);
    }
    if (createdAt_ != null) {
      output.writeMessage(6, getCreatedAt());
    }
    if (updatedAt_ != null) {
      output.writeMessage(7, getUpdatedAt());
    }
    if (typeUpdatedAt_ != null) {
      output.writeMessage(8, getTypeUpdatedAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(managerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, managerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, channelId_);
    }
    if (operatorStatusType_ != io.channel.api.proto.pub.coreapi.model.OperatorStatusType.OPERATOR_STATUS_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, operatorStatusType_);
    }
    if (enable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, enable_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCreatedAt());
    }
    if (updatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getUpdatedAt());
    }
    if (typeUpdatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getTypeUpdatedAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.model.OperatorStatus)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.model.OperatorStatus other = (io.channel.api.proto.pub.coreapi.model.OperatorStatus) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getManagerId()
        .equals(other.getManagerId())) return false;
    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (operatorStatusType_ != other.operatorStatusType_) return false;
    if (getEnable()
        != other.getEnable()) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (hasTypeUpdatedAt() != other.hasTypeUpdatedAt()) return false;
    if (hasTypeUpdatedAt()) {
      if (!getTypeUpdatedAt()
          .equals(other.getTypeUpdatedAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + MANAGER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManagerId().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    hash = (37 * hash) + OPERATOR_STATUS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + operatorStatusType_;
    hash = (37 * hash) + ENABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnable());
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    if (hasTypeUpdatedAt()) {
      hash = (37 * hash) + TYPE_UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getTypeUpdatedAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.model.OperatorStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * OperatorStatus represents the operational status of a manager.
   * </pre>
   *
   * Protobuf type {@code coreapi.model.OperatorStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.model.OperatorStatus)
      io.channel.api.proto.pub.coreapi.model.OperatorStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.OperatorStatusOuterClass.internal_static_coreapi_model_OperatorStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.model.OperatorStatusOuterClass.internal_static_coreapi_model_OperatorStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.model.OperatorStatus.class, io.channel.api.proto.pub.coreapi.model.OperatorStatus.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.model.OperatorStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      managerId_ = "";

      channelId_ = "";

      operatorStatusType_ = 0;

      enable_ = false;

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }
      if (typeUpdatedAtBuilder_ == null) {
        typeUpdatedAt_ = null;
      } else {
        typeUpdatedAt_ = null;
        typeUpdatedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.model.OperatorStatusOuterClass.internal_static_coreapi_model_OperatorStatus_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.OperatorStatus getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.model.OperatorStatus.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.OperatorStatus build() {
      io.channel.api.proto.pub.coreapi.model.OperatorStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.OperatorStatus buildPartial() {
      io.channel.api.proto.pub.coreapi.model.OperatorStatus result = new io.channel.api.proto.pub.coreapi.model.OperatorStatus(this);
      result.id_ = id_;
      result.managerId_ = managerId_;
      result.channelId_ = channelId_;
      result.operatorStatusType_ = operatorStatusType_;
      result.enable_ = enable_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      if (updatedAtBuilder_ == null) {
        result.updatedAt_ = updatedAt_;
      } else {
        result.updatedAt_ = updatedAtBuilder_.build();
      }
      if (typeUpdatedAtBuilder_ == null) {
        result.typeUpdatedAt_ = typeUpdatedAt_;
      } else {
        result.typeUpdatedAt_ = typeUpdatedAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.model.OperatorStatus) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.model.OperatorStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.model.OperatorStatus other) {
      if (other == io.channel.api.proto.pub.coreapi.model.OperatorStatus.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getManagerId().isEmpty()) {
        managerId_ = other.managerId_;
        onChanged();
      }
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        onChanged();
      }
      if (other.operatorStatusType_ != 0) {
        setOperatorStatusTypeValue(other.getOperatorStatusTypeValue());
      }
      if (other.getEnable() != false) {
        setEnable(other.getEnable());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      if (other.hasTypeUpdatedAt()) {
        mergeTypeUpdatedAt(other.getTypeUpdatedAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.model.OperatorStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.model.OperatorStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique operator status identifier.
     * Same as the manager ID.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique operator status identifier.
     * Same as the manager ID.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique operator status identifier.
     * Same as the manager ID.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique operator status identifier.
     * Same as the manager ID.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique operator status identifier.
     * Same as the manager ID.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object managerId_ = "";
    /**
     * <pre>
     * ID of the manager this status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
     * @return The managerId.
     */
    public java.lang.String getManagerId() {
      java.lang.Object ref = managerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        managerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the manager this status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for managerId.
     */
    public com.google.protobuf.ByteString
        getManagerIdBytes() {
      java.lang.Object ref = managerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        managerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the manager this status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
     * @param value The managerId to set.
     * @return This builder for chaining.
     */
    public Builder setManagerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      managerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the manager this status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearManagerId() {
      
      managerId_ = getDefaultInstance().getManagerId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the manager this status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string manager_id = 2 [json_name = "managerId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for managerId to set.
     * @return This builder for chaining.
     */
    public Builder setManagerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      managerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <pre>
     * Channel ID this operator status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Channel ID this operator status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Channel ID this operator status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID this operator status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      
      channelId_ = getDefaultInstance().getChannelId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID this operator status belongs to.
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinLength=1
     * </pre>
     *
     * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channelId_ = value;
      onChanged();
      return this;
    }

    private int operatorStatusType_ = 0;
    /**
     * <pre>
     * Current activity type of the operator.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
     * @return The enum numeric value on the wire for operatorStatusType.
     */
    @java.lang.Override public int getOperatorStatusTypeValue() {
      return operatorStatusType_;
    }
    /**
     * <pre>
     * Current activity type of the operator.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
     * @param value The enum numeric value on the wire for operatorStatusType to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorStatusTypeValue(int value) {
      
      operatorStatusType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current activity type of the operator.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
     * @return The operatorStatusType.
     */
    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.OperatorStatusType getOperatorStatusType() {
      @SuppressWarnings("deprecation")
      io.channel.api.proto.pub.coreapi.model.OperatorStatusType result = io.channel.api.proto.pub.coreapi.model.OperatorStatusType.valueOf(operatorStatusType_);
      return result == null ? io.channel.api.proto.pub.coreapi.model.OperatorStatusType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Current activity type of the operator.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
     * @param value The operatorStatusType to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorStatusType(io.channel.api.proto.pub.coreapi.model.OperatorStatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operatorStatusType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current activity type of the operator.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.coreapi.model.OperatorStatusType operator_status_type = 4 [json_name = "operatorStatusType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorStatusType() {
      
      operatorStatusType_ = 0;
      onChanged();
      return this;
    }

    private boolean enable_ ;
    /**
     * <pre>
     * Whether the operator is enabled for assignment.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool enable = 5 [json_name = "enable"];</code>
     * @return The enable.
     */
    @java.lang.Override
    public boolean getEnable() {
      return enable_;
    }
    /**
     * <pre>
     * Whether the operator is enabled for assignment.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool enable = 5 [json_name = "enable"];</code>
     * @param value The enable to set.
     * @return This builder for chaining.
     */
    public Builder setEnable(boolean value) {
      
      enable_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the operator is enabled for assignment.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool enable = 5 [json_name = "enable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnable() {
      
      enable_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <pre>
     * Operator status creation timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return updatedAtBuilder_ != null || updatedAt_ != null;
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (updatedAt_ != null) {
          updatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
        } else {
          updatedAt_ = value;
        }
        onChanged();
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
        onChanged();
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <pre>
     * Operator status last update timestamp.
     * +kubebuilder:validation:Required
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private com.google.protobuf.Timestamp typeUpdatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> typeUpdatedAtBuilder_;
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     * @return Whether the typeUpdatedAt field is set.
     */
    public boolean hasTypeUpdatedAt() {
      return typeUpdatedAtBuilder_ != null || typeUpdatedAt_ != null;
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     * @return The typeUpdatedAt.
     */
    public com.google.protobuf.Timestamp getTypeUpdatedAt() {
      if (typeUpdatedAtBuilder_ == null) {
        return typeUpdatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : typeUpdatedAt_;
      } else {
        return typeUpdatedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public Builder setTypeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (typeUpdatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        typeUpdatedAt_ = value;
        onChanged();
      } else {
        typeUpdatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public Builder setTypeUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (typeUpdatedAtBuilder_ == null) {
        typeUpdatedAt_ = builderForValue.build();
        onChanged();
      } else {
        typeUpdatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public Builder mergeTypeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (typeUpdatedAtBuilder_ == null) {
        if (typeUpdatedAt_ != null) {
          typeUpdatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(typeUpdatedAt_).mergeFrom(value).buildPartial();
        } else {
          typeUpdatedAt_ = value;
        }
        onChanged();
      } else {
        typeUpdatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public Builder clearTypeUpdatedAt() {
      if (typeUpdatedAtBuilder_ == null) {
        typeUpdatedAt_ = null;
        onChanged();
      } else {
        typeUpdatedAt_ = null;
        typeUpdatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTypeUpdatedAtBuilder() {
      
      onChanged();
      return getTypeUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTypeUpdatedAtOrBuilder() {
      if (typeUpdatedAtBuilder_ != null) {
        return typeUpdatedAtBuilder_.getMessageOrBuilder();
      } else {
        return typeUpdatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : typeUpdatedAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when the operator status type was last changed.
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>.google.protobuf.Timestamp type_updated_at = 8 [json_name = "typeUpdatedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTypeUpdatedAtFieldBuilder() {
      if (typeUpdatedAtBuilder_ == null) {
        typeUpdatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTypeUpdatedAt(),
                getParentForChildren(),
                isClean());
        typeUpdatedAt_ = null;
      }
      return typeUpdatedAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearId(java.lang.String value) {
    	if (value == null)
    		return clearId();
    	else
    		return setId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearId();
    	else
    		return setId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The manager_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearManagerId(java.lang.String value) {
    	if (value == null)
    		return clearManagerId();
    	else
    		return setManagerId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearManagerId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearManagerId();
    	else
    		return setManagerId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The channel_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChannelId(java.lang.String value) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChannelId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The operator_status_type to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearOperatorStatusType(io.channel.api.proto.pub.coreapi.model.OperatorStatusType value) {
    	if (value == null)
    		return clearOperatorStatusType();
    	else
    		return setOperatorStatusType(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearOperatorStatusType(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.OperatorStatusType> mapFunc) {
    	if (value == null)
    		return clearOperatorStatusType();
    	else
    		return setOperatorStatusType(mapFunc.apply(value));
    }
    	
    /**
     * @param value The enable to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearEnable(java.lang.Boolean value) {
    	if (value == null)
    		return clearEnable();
    	else
    		return setEnable(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearEnable(T value, java.util.function.Function<T, java.lang.Boolean> mapFunc) {
    	if (value == null)
    		return clearEnable();
    	else
    		return setEnable(mapFunc.apply(value));
    }
    	
    /**
     * @param value The created_at to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearCreatedAt(com.google.protobuf.Timestamp value) {
    	if (value == null)
    		return clearCreatedAt();
    	else
    		return setCreatedAt(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearCreatedAt(T value, java.util.function.Function<T, com.google.protobuf.Timestamp> mapFunc) {
    	if (value == null)
    		return clearCreatedAt();
    	else
    		return setCreatedAt(mapFunc.apply(value));
    }
    	
    /**
     * @param value The updated_at to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearUpdatedAt(com.google.protobuf.Timestamp value) {
    	if (value == null)
    		return clearUpdatedAt();
    	else
    		return setUpdatedAt(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearUpdatedAt(T value, java.util.function.Function<T, com.google.protobuf.Timestamp> mapFunc) {
    	if (value == null)
    		return clearUpdatedAt();
    	else
    		return setUpdatedAt(mapFunc.apply(value));
    }
    	
    /**
     * @param value The type_updated_at to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearTypeUpdatedAt(com.google.protobuf.Timestamp value) {
    	if (value == null)
    		return clearTypeUpdatedAt();
    	else
    		return setTypeUpdatedAt(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearTypeUpdatedAt(T value, java.util.function.Function<T, com.google.protobuf.Timestamp> mapFunc) {
    	if (value == null)
    		return clearTypeUpdatedAt();
    	else
    		return setTypeUpdatedAt(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.model.OperatorStatus)
  }

  // @@protoc_insertion_point(class_scope:coreapi.model.OperatorStatus)
  private static final io.channel.api.proto.pub.coreapi.model.OperatorStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.model.OperatorStatus();
  }

  public static io.channel.api.proto.pub.coreapi.model.OperatorStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperatorStatus>
      PARSER = new com.google.protobuf.AbstractParser<OperatorStatus>() {
    @java.lang.Override
    public OperatorStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OperatorStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OperatorStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperatorStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.OperatorStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
