// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/plugin.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * Vertical position of the mobile chat bubble.
 * </pre>
 *
 * Protobuf enum {@code coreapi.model.PluginBubblePosition}
 */
public enum PluginBubblePosition
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLUGIN_BUBBLE_POSITION_UNSPECIFIED = 0;</code>
   */
  PLUGIN_BUBBLE_POSITION_UNSPECIFIED(0),
  /**
   * <code>PLUGIN_BUBBLE_POSITION_TOP = 1;</code>
   */
  PLUGIN_BUBBLE_POSITION_TOP(1),
  /**
   * <code>PLUGIN_BUBBLE_POSITION_BOTTOM = 2;</code>
   */
  PLUGIN_BUBBLE_POSITION_BOTTOM(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLUGIN_BUBBLE_POSITION_UNSPECIFIED = 0;</code>
   */
  public static final int PLUGIN_BUBBLE_POSITION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PLUGIN_BUBBLE_POSITION_TOP = 1;</code>
   */
  public static final int PLUGIN_BUBBLE_POSITION_TOP_VALUE = 1;
  /**
   * <code>PLUGIN_BUBBLE_POSITION_BOTTOM = 2;</code>
   */
  public static final int PLUGIN_BUBBLE_POSITION_BOTTOM_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PluginBubblePosition valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PluginBubblePosition forNumber(int value) {
    switch (value) {
      case 0: return PLUGIN_BUBBLE_POSITION_UNSPECIFIED;
      case 1: return PLUGIN_BUBBLE_POSITION_TOP;
      case 2: return PLUGIN_BUBBLE_POSITION_BOTTOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PluginBubblePosition>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PluginBubblePosition> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PluginBubblePosition>() {
          public PluginBubblePosition findValueByNumber(int number) {
            return PluginBubblePosition.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.PluginOuterClass.getDescriptor().getEnumTypes().get(3);
  }

  private static final PluginBubblePosition[] VALUES = values();

  public static PluginBubblePosition valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PluginBubblePosition(int value) {
    this.value = value;
  }

  /* Generated by protoc-gen-java-canonical-enum-namings */
  
  /**
   * @param value The string value corresponding to the enum entry.
   * @return The enum entry corresponding to the string value.
   */
  public static PluginBubblePosition forString(String value) {
  	switch (value) {
      case "bottom": return PLUGIN_BUBBLE_POSITION_BOTTOM;
      case "top": return PLUGIN_BUBBLE_POSITION_TOP;
  		default: return PLUGIN_BUBBLE_POSITION_UNSPECIFIED;
  	}
  }
  				
  /**
   * @return The string value corresponding to the enum entry.
   */
  public final String getString() {
  	switch (this) {
      case PLUGIN_BUBBLE_POSITION_BOTTOM: return "bottom";
      case PLUGIN_BUBBLE_POSITION_TOP: return "top";
  		default: return null;
  	}
  }
  				
  // @@protoc_insertion_point(enum_scope:coreapi.model.PluginBubblePosition)
}
