// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/plugin.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * Visual theme of the plugin widget.
 * </pre>
 *
 * Protobuf enum {@code coreapi.model.PluginAppearance}
 */
public enum PluginAppearance
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLUGIN_APPEARANCE_UNSPECIFIED = 0;</code>
   */
  PLUGIN_APPEARANCE_UNSPECIFIED(0),
  /**
   * <code>PLUGIN_APPEARANCE_LIGHT = 1;</code>
   */
  PLUGIN_APPEARANCE_LIGHT(1),
  /**
   * <code>PLUGIN_APPEARANCE_DARK = 2;</code>
   */
  PLUGIN_APPEARANCE_DARK(2),
  /**
   * <code>PLUGIN_APPEARANCE_SYSTEM = 3;</code>
   */
  PLUGIN_APPEARANCE_SYSTEM(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLUGIN_APPEARANCE_UNSPECIFIED = 0;</code>
   */
  public static final int PLUGIN_APPEARANCE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PLUGIN_APPEARANCE_LIGHT = 1;</code>
   */
  public static final int PLUGIN_APPEARANCE_LIGHT_VALUE = 1;
  /**
   * <code>PLUGIN_APPEARANCE_DARK = 2;</code>
   */
  public static final int PLUGIN_APPEARANCE_DARK_VALUE = 2;
  /**
   * <code>PLUGIN_APPEARANCE_SYSTEM = 3;</code>
   */
  public static final int PLUGIN_APPEARANCE_SYSTEM_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PluginAppearance valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PluginAppearance forNumber(int value) {
    switch (value) {
      case 0: return PLUGIN_APPEARANCE_UNSPECIFIED;
      case 1: return PLUGIN_APPEARANCE_LIGHT;
      case 2: return PLUGIN_APPEARANCE_DARK;
      case 3: return PLUGIN_APPEARANCE_SYSTEM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PluginAppearance>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PluginAppearance> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PluginAppearance>() {
          public PluginAppearance findValueByNumber(int number) {
            return PluginAppearance.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.PluginOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final PluginAppearance[] VALUES = values();

  public static PluginAppearance valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PluginAppearance(int value) {
    this.value = value;
  }

  /* Generated by protoc-gen-java-canonical-enum-namings */
  
  /**
   * @param value The string value corresponding to the enum entry.
   * @return The enum entry corresponding to the string value.
   */
  public static PluginAppearance forString(String value) {
  	switch (value) {
      case "dark": return PLUGIN_APPEARANCE_DARK;
      case "light": return PLUGIN_APPEARANCE_LIGHT;
      case "system": return PLUGIN_APPEARANCE_SYSTEM;
  		default: return PLUGIN_APPEARANCE_UNSPECIFIED;
  	}
  }
  				
  /**
   * @return The string value corresponding to the enum entry.
   */
  public final String getString() {
  	switch (this) {
      case PLUGIN_APPEARANCE_DARK: return "dark";
      case PLUGIN_APPEARANCE_LIGHT: return "light";
      case PLUGIN_APPEARANCE_SYSTEM: return "system";
  		default: return null;
  	}
  }
  				
  // @@protoc_insertion_point(enum_scope:coreapi.model.PluginAppearance)
}
